import type { Exercise } from './exercises';

let nextId = 2001;
function ex(partial: Omit<Exercise, 'id'>): Exercise {
  return { id: nextId++, ...partial };
}

export const B2_EXERCISES: Exercise[] = [
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to be at a loss for words / speechless', answer: 'ficar sem palavras', distractors: null, explanation: '"Ficar sem palavras" = to be left without words. More formal: "ficar estupefato" (stunned).', mineiro_note: '"Nó, fiquei sem palavras!" — classic Mineiro reaction', tags: '["emotions","B2"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to hold a grudge', answer: 'guardar rancor', distractors: null, explanation: '"Guardar" = to keep/hold, "rancor" = grudge/resentment. "Não guardo rancor" = I don\'t hold grudges.', mineiro_note: null, tags: '["emotions","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'work', prompt: 'to be overloaded with work', answer: 'estar sobrecarregado', distractors: null, explanation: '"Sobrecarregado" = overloaded. "Estou sobrecarregado de trabalho" = I\'m overloaded with work.', mineiro_note: null, tags: '["work","B2"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'work', prompt: 'to network (professionally)', answer: 'fazer networking', distractors: null, explanation: 'English loanword commonly used in Brazilian Portuguese. Also: "fazer contatos profissionais".', mineiro_note: null, tags: '["work","B2"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'daily_routine', prompt: 'to procrastinate', answer: 'procrastinar', distractors: null, explanation: 'Same root as English. Very commonly used in Brazilian Portuguese. "Parei de procrastinar" = I stopped procrastinating.', mineiro_note: null, tags: '["daily_routine","B2"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'mineiro', prompt: '"old man" / "buddy" (affectionate Mineiro slang)', answer: 'véio', distractors: null, explanation: 'Contracted from "velho" (old). Used affectionately between friends regardless of age. "E aí, véio!" = Hey buddy!', mineiro_note: '"Ô véio, cê tá sumido!" = "Hey buddy, you disappeared!"', tags: '["mineiro","B2"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'verbs_present', prompt: 'Embora ele ___ inteligente, não passou no exame. (Although he is intelligent, he didn\'t pass — ser, present subjunctive)', answer: 'seja', distractors: null, explanation: '"Embora" (although) always triggers subjunctive. "Seja" = present subjunctive of "ser".', mineiro_note: null, tags: '["verbs","subjunctive","B2"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'verbs_past', prompt: 'Depois que eles ___, nós fomos embora. (After they left, we left — sair, past subjunctive/pluperfect)', answer: 'saíram', distractors: null, explanation: 'Preterite of "sair" (3rd plural). "Depois que" + indicative describes a completed sequence of events.', mineiro_note: null, tags: '["verbs","B2"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'verbs_present', prompt: 'Ela fala como se ___ brasileira. (She speaks as if she were Brazilian — ser, imperfect subjunctive)', answer: 'fosse', distractors: null, explanation: '"Como se" (as if) always requires imperfect subjunctive. "Fosse" = imperfect subjunctive of "ser".', mineiro_note: null, tags: '["verbs","subjunctive","B2"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'prepositions', prompt: 'Apesar ___ chuva, fomos ao parque. (Despite the rain, we went to the park)', answer: 'da', distractors: null, explanation: '"Apesar de" = despite. "Da" = de + a (contraction with feminine "chuva"). Complex preposition usage.', mineiro_note: null, tags: '["preposition","B2"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'B2', topic: 'cultural', prompt: 'What is "Clube da Esquina"?', answer: 'A legendary music movement from Minas Gerais (Milton Nascimento)', distractors: '["A soccer club from BH","A Mineiro cooking school","A political party"]', explanation: 'Clube da Esquina is one of the most influential music movements in Brazilian history, centered in BH. Led by Milton Nascimento, Lô Borges, and others in the 1970s.', mineiro_note: 'Milton Nascimento is Minas\'s greatest musician — his voice is iconic worldwide.', tags: '["cultural","B2"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'B2', topic: 'cultural', prompt: 'What does "mineiridade" refer to?', answer: 'The cultural identity and character traits of people from Minas Gerais', distractors: '["A type of mineral","The mining industry","A political movement"]', explanation: '"Mineiridade" encompasses discretion, hospitality, love of food, religious tradition, and a reserved but warm personality. Mineiros are known for being reserved but deeply loyal.', mineiro_note: '"Mineiro não fala o que pensa, mas pensa muito no que fala" — a famous saying about Mineiro discretion.', tags: '["cultural","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to lend a hand / to help (idiom)', answer: 'dar uma mão', distractors: null, explanation: 'Literally "to give a hand." "Cê pode me dar uma mão aqui?"', mineiro_note: null, tags: '["emotions","idiom","B2"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to break the ice (idiom)', answer: 'quebrar o gelo', distractors: null, explanation: 'Same expression as English! Used when easing social awkwardness.', mineiro_note: null, tags: '["emotions","idiom","B2"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to leave quickly / bolt (idiom)', answer: 'meter o pé', distractors: null, explanation: '"Meter o pé" = to get out fast. "Quando viu a chuva, meteu o pé!"', mineiro_note: null, tags: '["emotions","idiom","B2"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to turn a blind eye (idiom)', answer: 'fazer vista grossa', distractors: null, explanation: 'To pretend not to see. "O chefe fez vista grossa pro atraso."', mineiro_note: null, tags: '["emotions","idiom","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to swallow one\'s pride / endure (idiom)', answer: 'engolir sapo', distractors: null, explanation: 'Literally "to swallow a frog." Endure something unpleasant without complaining.', mineiro_note: null, tags: '["emotions","idiom","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to mess up / drop the ball (idiom)', answer: 'pisar na bola', distractors: null, explanation: '"Ele pisou na bola com a namorada." = He messed up with his girlfriend.', mineiro_note: null, tags: '["emotions","idiom","B2"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to manage / handle / cope (idiom)', answer: 'dar conta', distractors: null, explanation: '"Cê dá conta de fazer isso sozinho?" Different from "pagar a conta" (pay the bill).', mineiro_note: '"Nó, não tô dano conta de tanto trabalho, sô!"', tags: '["emotions","idiom","B2"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to be flexible / resourceful (idiom)', answer: 'ter jogo de cintura', distractors: null, explanation: 'Literally "to have waist game." Being adaptable in tricky situations.', mineiro_note: null, tags: '["emotions","idiom","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'soul', answer: 'alma', distractors: null, explanation: 'Common in Brazilian music and literature.', mineiro_note: null, tags: '["emotions","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'destiny / fate', answer: 'destino', distractors: null, explanation: 'Also means "destination" in travel contexts.', mineiro_note: null, tags: '["emotions","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'freedom', answer: 'liberdade', distractors: null, explanation: 'The Inconfidência Mineira was a freedom movement in Minas.', mineiro_note: null, tags: '["emotions","cultural","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'wisdom', answer: 'sabedoria', distractors: null, explanation: 'From "saber" (to know).', mineiro_note: null, tags: '["emotions","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'courage', answer: 'coragem', distractors: null, explanation: '"Coragem!" = Be brave! Used as encouragement.', mineiro_note: null, tags: '["emotions","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'gratitude', answer: 'gratidão', distractors: null, explanation: '"Grato/grata" = grateful.', mineiro_note: null, tags: '["emotions","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'resilience', answer: 'resiliência', distractors: null, explanation: 'Widely used in modern Brazilian Portuguese.', mineiro_note: null, tags: '["emotions","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'work', prompt: 'investment', answer: 'investimento', distractors: null, explanation: '"Investir" = to invest.', mineiro_note: null, tags: '["work","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'work', prompt: 'profit', answer: 'lucro', distractors: null, explanation: '"Lucrativo" = profitable.', mineiro_note: null, tags: '["work","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'work', prompt: 'loss (financial)', answer: 'prejuízo', distractors: null, explanation: '"Dar prejuízo" = to cause a loss.', mineiro_note: null, tags: '["work","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'work', prompt: 'entrepreneur', answer: 'empreendedor', distractors: null, explanation: 'Brazil has a strong entrepreneurial culture.', mineiro_note: null, tags: '["work","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'work', prompt: 'innovation', answer: 'inovação', distractors: null, explanation: '"Inovar" = to innovate.', mineiro_note: null, tags: '["work","B2"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'verbs_present', prompt: 'Quando eu ___, vou te ajudar. (poder — future subjunctive)', answer: 'puder', distractors: null, explanation: 'Future subjunctive of "poder". Used after "quando" for future conditions.', mineiro_note: null, tags: '["verbs","subjunctive","B2"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'verbs_present', prompt: 'Se você ___, venha me visitar. (querer — future subjunctive)', answer: 'quiser', distractors: null, explanation: 'Future subjunctive of "querer". "Se você quiser" = If you want.', mineiro_note: null, tags: '["verbs","subjunctive","B2"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'verbs_present', prompt: 'Onde você ___, eu vou também. (ir — future subjunctive)', answer: 'for', distractors: null, explanation: 'Future subjunctive of "ir" (and "ser"). "Onde você for" = Wherever you go.', mineiro_note: null, tags: '["verbs","subjunctive","B2"]', difficulty: 3 }),
];
