import type { Exercise } from './exercises';

let nextId = 3001;
function ex(partial: Omit<Exercise, 'id'>): Exercise {
  return { id: nextId++, ...partial };
}

export const C1_EXERCISES: Exercise[] = [
  // === ADVANCED SUBJUNCTIVE ===
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Caso ele ___ tempo, vai nos visitar. (If he has time — ter, future subjunctive)', answer: 'tiver', distractors: null, explanation: '"Caso" triggers subjunctive. "Tiver" = future subjunctive of "ter". Portuguese uses future subjunctive where English uses present.', mineiro_note: null, tags: '["subjunctive","C1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Quando eu ___ a verdade, vou te contar. (When I find out — saber, future subjunctive)', answer: 'souber', distractors: null, explanation: '"Souber" = irregular future subjunctive of "saber". Used with "quando" for future uncertainty.', mineiro_note: null, tags: '["subjunctive","C1"]', difficulty: 4 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Se eu ___ rico, viajaria pelo mundo. (If I were — ser, imperfect subjunctive)', answer: 'fosse', distractors: null, explanation: '"Se" + imperfect subjunctive for contrary-to-fact conditions. "Fosse" from "ser".', mineiro_note: '"Se eu fosse cê, ia embora, uai."', tags: '["subjunctive","conditional","C1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_past', prompt: 'Se ele ___ mais cedo, teria pegado o ônibus. (If he had left — sair, pluperfect subjunctive)', answer: 'tivesse saído', distractors: null, explanation: 'Pluperfect subjunctive: "tivesse" + past participle. For hypothetical past events.', mineiro_note: null, tags: '["subjunctive","C1"]', difficulty: 4 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Oxalá ele ___ a tempo. (I hope he arrives in time — chegar, present subjunctive)', answer: 'chegue', distractors: null, explanation: '"Oxalá" (from Arabic) = I hope/God willing. Always triggers present subjunctive.', mineiro_note: null, tags: '["subjunctive","C1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Onde quer que cê ___, eu vou te achar. (Wherever you go — ir, present subjunctive)', answer: 'vá', distractors: null, explanation: '"Onde quer que" = wherever. Requires subjunctive. "Vá" = present subjunctive of "ir".', mineiro_note: '"Cê vai pra onde cê quiser, sô!"', tags: '["subjunctive","C1"]', difficulty: 3 }),

  // === FORMAL vs INFORMAL REGISTER ===
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'Dear Sir/Madam (formal letter opening)', answer: 'Prezado(a) Senhor(a)', distractors: null, explanation: '"Prezado" = esteemed/dear. Used in formal correspondence. Never use in casual context.', mineiro_note: 'Mineiros in formal settings are extremely polite — more formal than other Brazilians.', tags: '["formal","work","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'I would like to inform you that... (formal)', answer: 'Venho por meio desta informar que...', distractors: null, explanation: 'Very formal construction. "Venho por meio desta" = "I come by means of this [letter/email]".', mineiro_note: null, tags: '["formal","work","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'Yours sincerely / Best regards (formal closing)', answer: 'Atenciosamente', distractors: null, explanation: 'The standard formal email closing. Also: "Cordialmente" (cordially).', mineiro_note: null, tags: '["formal","work","C1"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'C1', topic: 'work', prompt: 'Fix the register: "E aí, chefe! Queria pedir um aumento, beleza?"', answer: 'Prezado(a), gostaria de solicitar uma revisão salarial.', distractors: null, explanation: 'The original is way too informal for requesting a raise. "Solicitar" instead of "pedir", "revisão salarial" instead of "aumento".', mineiro_note: 'Even in Minas, formal requests must use formal Portuguese — save the "uai" for after work!', tags: '["register","work","C1"]', difficulty: 3 }),

  // === ADVANCED IDIOMS ===
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'to be between a rock and a hard place (idiom)', answer: 'estar entre a cruz e a espada', distractors: null, explanation: 'Literally "between the cross and the sword." Facing two bad options.', mineiro_note: null, tags: '["idiom","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'to add fuel to the fire (idiom)', answer: 'botar lenha na fogueira', distractors: null, explanation: '"Botar" = to put (informal), "lenha" = firewood. Making a situation worse.', mineiro_note: '"Não bota mais lenha nessa fogueira não, sô!"', tags: '["idiom","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'to beat around the bush (idiom)', answer: 'enrolar', distractors: null, explanation: '"Para de enrolar e fala logo!" = Stop beating around the bush and just say it!', mineiro_note: '"Mineiro enrola, enrola, mas no final sempre fala a verdade."', tags: '["idiom","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'the last straw (idiom)', answer: 'a gota d\'água', distractors: null, explanation: 'Literally "the drop of water" (that overflows the glass). "Foi a gota d\'água!"', mineiro_note: null, tags: '["idiom","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'to pull someone\'s leg / tease (idiom)', answer: 'tirar sarro', distractors: null, explanation: '"Eles tiraram sarro da minha cara." = They made fun of me. Can be playful or mean.', mineiro_note: null, tags: '["idiom","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'to have butterflies in your stomach (idiom)', answer: 'estar com frio na barriga', distractors: null, explanation: 'Literally "to have cold in the belly." Nervousness/excitement before something big.', mineiro_note: null, tags: '["idiom","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'to let the cat out of the bag (idiom)', answer: 'dar com a língua nos dentes', distractors: null, explanation: '"Hit the tongue against the teeth" = to reveal a secret accidentally.', mineiro_note: null, tags: '["idiom","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'to give up / throw in the towel (idiom)', answer: 'jogar a toalha', distractors: null, explanation: 'Same metaphor as English — from boxing. "Não jogue a toalha!"', mineiro_note: null, tags: '["idiom","C1"]', difficulty: 2 }),

  // === LITERARY/CULTURAL PORTUGUESE ===
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'cultural', prompt: 'nostalgia / longing (untranslatable Portuguese concept)', answer: 'saudade', distractors: null, explanation: '"Saudade" has no exact English equivalent — it\'s a deep emotional state of longing for something absent. Central to Brazilian culture and music.', mineiro_note: '"Mineiro tem saudade até do que nunca viveu."', tags: '["cultural","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'cultural', prompt: 'the Brazilian way of getting things done creatively', answer: 'jeitinho brasileiro', distractors: null, explanation: '"Jeitinho" = a clever workaround. Can be positive (resourcefulness) or negative (bending rules). Central concept in Brazilian culture.', mineiro_note: '"Mineiro tem jeitinho pra tudo — dá um jeito onde ninguém dá."', tags: '["cultural","C1"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'C1', topic: 'cultural', prompt: 'Who is considered the greatest Brazilian writer, often compared to Dostoevsky?', answer: 'Machado de Assis', distractors: '["Jorge Amado","Paulo Coelho","Clarice Lispector"]', explanation: 'Machado de Assis (1839-1908) is Brazil\'s greatest literary figure. His novels "Dom Casmurro" and "Memórias Póstumas de Brás Cubas" are masterpieces of world literature.', mineiro_note: null, tags: '["cultural","literature","C1"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'C1', topic: 'cultural', prompt: 'What does "Inconfidência Mineira" refer to?', answer: 'An 18th-century independence movement in Minas Gerais against Portuguese rule', distractors: '["A type of Mineiro cheese","A religious festival","A mining technique"]', explanation: 'Led by Tiradentes (Joaquim José da Silva Xavier), it was a failed 1789 conspiracy for Brazilian independence. Tiradentes was executed and became a national hero.', mineiro_note: '"Tiradentes é herói nacional — a cidade tem o nome dele!"', tags: '["cultural","history","C1"]', difficulty: 3 }),

  // === ADVANCED GRAMMAR: PERSONAL INFINITIVE ===
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_present', prompt: 'É importante ___ todos os documentos. (It\'s important for us to bring — trazer, personal infinitive)', answer: 'trazermos', distractors: null, explanation: 'Personal (inflected) infinitive: "trazermos" = for us to bring. Unique to Portuguese — doesn\'t exist in Spanish!', mineiro_note: null, tags: '["personal_infinitive","C1"]', difficulty: 4 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Antes de vocês ___, preciso falar algo. (Before you all leave — sair, personal infinitive)', answer: 'saírem', distractors: null, explanation: '"Saírem" = personal infinitive 3rd person plural. "Antes de" + personal infinitive is very common.', mineiro_note: null, tags: '["personal_infinitive","C1"]', difficulty: 4 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Apesar de ___ cansados, continuaram trabalhando. (Despite being — estar, personal infinitive)', answer: 'estarem', distractors: null, explanation: '"Apesar de" + personal infinitive. "Estarem" = they being. The personal infinitive agrees with the subject.', mineiro_note: null, tags: '["personal_infinitive","C1"]', difficulty: 4 }),

  // === ADVANCED CONNECTORS & DISCOURSE ===
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'nevertheless / however (formal connector)', answer: 'contudo / todavia', distractors: null, explanation: 'Formal alternatives to "mas" (but) and "porém" (however). Used in academic and professional writing.', mineiro_note: null, tags: '["connector","formal","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'therefore / consequently (formal connector)', answer: 'portanto / consequentemente', distractors: null, explanation: '"Portanto" is more common in speech; "consequentemente" in formal writing. Both stronger than "então".', mineiro_note: null, tags: '["connector","formal","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'in addition / furthermore (formal connector)', answer: 'além disso / ademais', distractors: null, explanation: '"Além disso" = besides that. "Ademais" is very formal, used in academic contexts.', mineiro_note: null, tags: '["connector","formal","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'on the other hand (formal connector)', answer: 'por outro lado', distractors: null, explanation: 'Used to present a contrasting viewpoint. "Por um lado... por outro lado..." = on one hand... on the other hand...', mineiro_note: null, tags: '["connector","formal","C1"]', difficulty: 2 }),

  // === MINEIRO DEEP CUTS ===
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'mineiro', prompt: '"What\'s up?" / "What happened?" (Mineiro)', answer: 'Qual foi?', distractors: null, explanation: 'Very Mineiro greeting/question. Can be confrontational ("what\'s your problem?") or friendly depending on tone.', mineiro_note: '"Ô sô, qual foi?" — classic BH opening', tags: '["mineiro","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'mineiro', prompt: '"no way!" / "seriously?!" (Mineiro exclamation)', answer: 'Nó, mãe!', distractors: null, explanation: 'Shortened from "Nossa Senhora!" (Our Lady!) — the full Mineiro exclamation. Stronger than just "Nó!"', mineiro_note: '"Nó, mãe! Cê viu o preço do queijo?!"', tags: '["mineiro","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'mineiro', prompt: '"a real mess" / "chaos" (Mineiro slang)', answer: 'trem doido', distractors: null, explanation: 'Literally "crazy thing." "Trem doido" describes any chaotic or unbelievable situation.', mineiro_note: '"Uai, que trem doido aconteceu no jogo ontem!"', tags: '["mineiro","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'mineiro', prompt: '"to gossip" / "to chat idly" (Mineiro)', answer: 'prosear', distractors: null, explanation: '"Prosear" = to have a leisurely chat. More positive than "fofocar" (to gossip). Central to Mineiro social life.', mineiro_note: '"Vamo prosear ali no bar, sô?" — classic Mineiro invitation', tags: '["mineiro","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'mineiro', prompt: '"cheap" / "stingy" (Mineiro stereotype, affectionate)', answer: 'pão-duro', distractors: null, explanation: 'Literally "hard bread." Mineiros have a (friendly) reputation for being frugal. "Mineiro é pão-duro mesmo, uai!"', mineiro_note: '"Mineiro não é pão-duro, é econômico!" — the classic defense', tags: '["mineiro","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'mineiro', prompt: '"to trick" / "to deceive" (colloquial)', answer: 'passar a perna', distractors: null, explanation: '"Ele passou a perna no colega." = He tricked his colleague. Very common colloquial expression.', mineiro_note: null, tags: '["mineiro","idiom","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'mineiro', prompt: '"it\'s far away" (Mineiro way of saying)', answer: 'é longe demais da conta', distractors: null, explanation: '"Demais da conta" is a uniquely Mineiro intensifier meaning "way too much." Standard: "muito longe."', mineiro_note: '"Ouro Preto? É longe demais da conta, sô!"', tags: '["mineiro","C1"]', difficulty: 2 }),

  // === ADVANCED ERROR CORRECTION ===
  ex({ type: 'error_correction', cefr_level: 'C1', topic: 'error_correction', prompt: 'Fix: "Eu sou cansado e sou com fome."', answer: 'Eu estou cansado e estou com fome.', distractors: null, explanation: 'Temporary states (tired, hungry) require "estar" not "ser." Classic Spanish interference — Spanish uses "estoy" for these too, but learners default to "ser".', mineiro_note: '"Tô cansado e com fome" — Mineiro shortens "estou" to "tô"', tags: '["ser_estar","error_correction","C1"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'C1', topic: 'error_correction', prompt: 'Fix: "Eu gosto do Brasil porque é um país muito calor."', answer: 'Eu gosto do Brasil porque é um país muito quente.', distractors: null, explanation: '"Calor" is a noun (heat); "quente" is the adjective (hot). "Faz calor" (it\'s hot weather) vs "o dia está quente" (the day is hot).', mineiro_note: null, tags: '["error_correction","C1"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'C1', topic: 'error_correction', prompt: 'Fix: "Nós foi no mercado e comprou muita coisa."', answer: 'Nós fomos ao mercado e compramos muita coisa.', distractors: null, explanation: 'Subject-verb agreement: "nós" requires 1st person plural (fomos, compramos). Also: "ir ao" not "ir no" in formal Portuguese.', mineiro_note: '"Nós foi" is actually common in spoken Mineiro but grammatically incorrect!', tags: '["agreement","error_correction","C1"]', difficulty: 3 }),
  ex({ type: 'error_correction', cefr_level: 'C1', topic: 'error_correction', prompt: 'Fix: "Ele me pediu para que eu faço o trabalho."', answer: 'Ele me pediu para que eu fizesse o trabalho.', distractors: null, explanation: '"Para que" + subjunctive. After "pediu" (past), the subjunctive must be imperfect: "fizesse" not "faço".', mineiro_note: null, tags: '["subjunctive","error_correction","C1"]', difficulty: 4 }),
  ex({ type: 'error_correction', cefr_level: 'C1', topic: 'error_correction', prompt: 'Fix: "A gente vamos sair amanhã."', answer: 'A gente vai sair amanhã.', distractors: null, explanation: '"A gente" (we, colloquial) takes 3rd person singular verb: "vai" not "vamos." "Nós vamos" OR "A gente vai" — never mix.', mineiro_note: '"A gente" is heavily used in Minas — more than "nós" in casual speech.', tags: '["agreement","error_correction","C1"]', difficulty: 3 }),

  // === ADVANCED REORDER ===
  ex({ type: 'reorder', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Reorder: caso / eu / tivesse / sabido / não / teria / ido', answer: 'Caso eu tivesse sabido, não teria ido.', distractors: null, explanation: 'Pluperfect subjunctive ("tivesse sabido") + conditional ("teria ido"). If I had known, I wouldn\'t have gone.', mineiro_note: null, tags: '["subjunctive","reorder","C1"]', difficulty: 4 }),
  ex({ type: 'reorder', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Reorder: por / mais / que / tentasse / não / conseguia', answer: 'Por mais que tentasse, não conseguia.', distractors: null, explanation: '"Por mais que" (no matter how much) + imperfect subjunctive. A concessive construction.', mineiro_note: null, tags: '["subjunctive","reorder","C1"]', difficulty: 4 }),

  // === TRUE/FALSE: CULTURAL KNOWLEDGE ===
  ex({ type: 'true_false', cefr_level: 'C1', topic: 'cultural', prompt: '"A gente" is considered grammatically incorrect in formal Portuguese.', answer: 'false', distractors: null, explanation: '"A gente" is grammatically valid and accepted by modern grammarians. It takes 3rd person singular conjugation. However, "nós" is preferred in formal writing.', mineiro_note: null, tags: '["grammar","cultural","C1"]', difficulty: 3 }),
  ex({ type: 'true_false', cefr_level: 'C1', topic: 'cultural', prompt: 'The future subjunctive tense exists in both Portuguese and Spanish.', answer: 'false', distractors: null, explanation: 'The future subjunctive is virtually extinct in modern Spanish but very much alive in Portuguese. "Quando eu puder" (when I can) vs Spanish "cuando pueda" (present subjunctive).', mineiro_note: null, tags: '["grammar","cultural","C1"]', difficulty: 3 }),
  ex({ type: 'true_false', cefr_level: 'C1', topic: 'cultural', prompt: 'The personal infinitive is a grammatical feature unique to Portuguese among Romance languages.', answer: 'true', distractors: null, explanation: 'The inflected/personal infinitive (infinitivo pessoal) is nearly unique to Portuguese. It allows infinitives to have person/number agreement: "para nós fazermos" vs Spanish "para que hagamos".', mineiro_note: null, tags: '["grammar","cultural","C1"]', difficulty: 4 }),
  ex({ type: 'true_false', cefr_level: 'C1', topic: 'mineiro', prompt: 'In Mineiro dialect, "trem" can refer to literally anything — objects, situations, people, food.', answer: 'true', distractors: null, explanation: '"Trem" is the ultimate Mineiro wildcard word. "Aquele trem" (that thing), "Que trem bão!" (what a great thing!), "Cadê o trem?" (where\'s the thing?). It replaces almost any noun.', mineiro_note: '"Passa aquele trem ali pra mim, sô" — could be anything from a salt shaker to a TV remote', tags: '["mineiro","C1"]', difficulty: 1 }),

  // === ADVANCED MULTIPLE CHOICE ===
  ex({ type: 'multiple_choice', cefr_level: 'C1', topic: 'verbs_present', prompt: 'Which sentence correctly uses the future subjunctive?', answer: 'Quando você puder, me liga.', distractors: '["Quando você pode, me liga.","Quando você pudesse, me liga.","Quando você poderia, me liga."]', explanation: '"Quando" + future subjunctive for uncertain future events. "Puder" = future subjunctive of "poder". The other options use wrong tenses.', mineiro_note: null, tags: '["subjunctive","C1"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'C1', topic: 'prepositions', prompt: 'Which is correct: "Eu assisti ___ filme" ?', answer: 'ao', distractors: '["o","no","pelo"]', explanation: '"Assistir" in the sense of "watch" requires the preposition "a" in formal Portuguese: "assistir ao filme." Colloquially, many Brazilians drop it.', mineiro_note: null, tags: '["preposition","C1"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'C1', topic: 'verbs_present', prompt: 'What is the personal infinitive of "fazer" for "nós"?', answer: 'fazermos', distractors: '["fazemos","fizéssemos","faríamos"]', explanation: 'Personal infinitive adds person endings to the infinitive: fazer + mos = fazermos. Different from present indicative (fazemos) or imperfect subjunctive (fizéssemos).', mineiro_note: null, tags: '["personal_infinitive","C1"]', difficulty: 4 }),

  // === ADVANCED VOCAB: ABSTRACT CONCEPTS ===
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'empathy', answer: 'empatia', distractors: null, explanation: 'Widely used in modern Brazilian Portuguese. "Ter empatia" = to have empathy.', mineiro_note: null, tags: '["emotions","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'consciousness / awareness', answer: 'consciência', distractors: null, explanation: 'Can mean both "consciousness" (philosophical) and "conscience" (moral). Context determines meaning.', mineiro_note: null, tags: '["emotions","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'emotions', prompt: 'integrity', answer: 'integridade', distractors: null, explanation: '"Uma pessoa de integridade" = a person of integrity. Highly valued concept.', mineiro_note: null, tags: '["emotions","C1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'sustainability', answer: 'sustentabilidade', distractors: null, explanation: 'Major topic in Brazilian discourse due to Amazon/environmental issues.', mineiro_note: null, tags: '["work","environment","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'bureaucracy', answer: 'burocracia', distractors: null, explanation: 'Brazil is famously bureaucratic. "A burocracia brasileira é de outro mundo."', mineiro_note: null, tags: '["work","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'work', prompt: 'to negotiate', answer: 'negociar', distractors: null, explanation: '"Negociação" = negotiation. "Vamos negociar os termos do contrato."', mineiro_note: null, tags: '["work","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'technology', prompt: 'artificial intelligence', answer: 'inteligência artificial', distractors: null, explanation: 'Often abbreviated as IA (not AI) in Portuguese.', mineiro_note: null, tags: '["technology","C1"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'technology', prompt: 'data privacy', answer: 'privacidade de dados', distractors: null, explanation: 'Brazil has LGPD (Lei Geral de Proteção de Dados) — similar to GDPR.', mineiro_note: null, tags: '["technology","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'technology', prompt: 'algorithm', answer: 'algoritmo', distractors: null, explanation: 'Same root as English. "O algoritmo das redes sociais."', mineiro_note: null, tags: '["technology","C1"]', difficulty: 1 }),

  // === FALSE COGNATES (ADVANCED) ===
  ex({ type: 'multiple_choice', cefr_level: 'C1', topic: 'false_cognates', prompt: '"Pretender" in Portuguese means:', answer: 'to intend / to plan', distractors: '["to pretend","to fake","to deceive"]', explanation: '"Pretender" = to intend. "Eu pretendo viajar" = I intend to travel. "To pretend" = "fingir" in Portuguese. Major false cognate!', mineiro_note: null, tags: '["false_cognate","C1"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'C1', topic: 'false_cognates', prompt: '"Puxar" in Portuguese means:', answer: 'to pull', distractors: '["to push","to punch","to poke"]', explanation: '"Puxar" = to pull (not push!). "Push" = "empurrar." Brazilians often write "puxe" on doors that you pull.', mineiro_note: null, tags: '["false_cognate","C1"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'C1', topic: 'false_cognates', prompt: '"Eventualmente" in Portuguese means:', answer: 'possibly / from time to time', distractors: '["eventually","finally","in the end"]', explanation: '"Eventualmente" = possibly/occasionally. "Eventually" = "finalmente" or "no final das contas." Common mistake for English speakers.', mineiro_note: null, tags: '["false_cognate","C1"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'C1', topic: 'false_cognates', prompt: '"Realizar" in Portuguese primarily means:', answer: 'to carry out / to accomplish', distractors: '["to realize (become aware)","to understand suddenly","to notice"]', explanation: '"Realizar" = to carry out/accomplish. "Realizar um projeto" = carry out a project. "To realize" = "perceber" or "dar-se conta."', mineiro_note: null, tags: '["false_cognate","C1"]', difficulty: 3 }),

  // === CLOZE: ADVANCED PREPOSITIONS ===
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'prepositions', prompt: 'Ele insistiu ___ ir sozinho. (He insisted on going alone)', answer: 'em', distractors: null, explanation: '"Insistir em" = to insist on. Portuguese uses "em" where English uses "on." Spanish uses "en" too, but the construction may differ.', mineiro_note: null, tags: '["preposition","C1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'prepositions', prompt: 'Eu sonho ___ morar em Minas. (I dream of living in Minas)', answer: 'em', distractors: null, explanation: '"Sonhar em" = to dream of. NOT "sonhar de" or "sonhar com" (which means "to dream about" in sleep).', mineiro_note: null, tags: '["preposition","C1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'prepositions', prompt: 'Depende ___ que cê quer fazer. (It depends on what you want to do)', answer: 'do', distractors: null, explanation: '"Depender de" = to depend on. "Do" = de + o (contraction). Always "de" after "depender."', mineiro_note: '"Depende do trem que cê quer, sô."', tags: '["preposition","C1"]', difficulty: 2 }),

  // === ADVANCED VOCAB: POLITICS & SOCIETY ===
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'cultural', prompt: 'inequality', answer: 'desigualdade', distractors: null, explanation: 'A central topic in Brazilian society. "Desigualdade social" = social inequality.', mineiro_note: null, tags: '["cultural","society","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'cultural', prompt: 'citizenship', answer: 'cidadania', distractors: null, explanation: '"Exercer a cidadania" = to exercise citizenship. Fundamental concept in Brazilian civics.', mineiro_note: null, tags: '["cultural","society","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'cultural', prompt: 'corruption', answer: 'corrupção', distractors: null, explanation: 'Major theme in Brazilian politics and media. "Combater a corrupção" = to fight corruption.', mineiro_note: null, tags: '["cultural","society","C1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'C1', topic: 'cultural', prompt: 'democracy', answer: 'democracia', distractors: null, explanation: '"Viver em democracia" = to live in a democracy. Brazil re-democratized in 1985.', mineiro_note: null, tags: '["cultural","society","C1"]', difficulty: 1 }),

  // === ADVANCED CLOZE: COMPOUND TENSES ===
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_past', prompt: 'Eu ___ trabalhando o dia inteiro. (I have been working all day — ter + gerund)', answer: 'tenho estado', distractors: null, explanation: '"Tenho estado" + gerund = present perfect continuous. More emphasis on ongoing nature than "tenho trabalhado."', mineiro_note: null, tags: '["compound_tense","C1"]', difficulty: 4 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_past', prompt: 'Eles já ___ quando eu cheguei. (They had already left — ter + past participle)', answer: 'tinham saído', distractors: null, explanation: 'Pluperfect: "tinham" (imperfect of ter) + "saído" (past participle). Had already left before another past action.', mineiro_note: null, tags: '["compound_tense","C1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'C1', topic: 'verbs_past', prompt: 'Até amanhã, eu ___ o relatório. (By tomorrow, I will have finished — ter + past participle, future)', answer: 'terei terminado', distractors: null, explanation: 'Future perfect: "terei" (future of ter) + past participle. Describes completion before a future point.', mineiro_note: null, tags: '["compound_tense","C1"]', difficulty: 4 }),
];
