/**
 * Hardcoded seed content for Phase 1.
 * This replaces the Python content generation pipeline for now —
 * enough exercises to practice for 2 weeks.
 *
 * In Phase 4, this will be replaced by SQLite content DB (fluent.db).
 */

import type { Exercise } from './exercises';

let nextId = 1;
function ex(partial: Omit<Exercise, 'id'>): Exercise {
  return { id: nextId++, ...partial };
}

export const SEED_EXERCISES: Exercise[] = [
  // === VOCAB: Food (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'bread (the round cheese bread from Minas)', answer: 'pão de queijo', distractors: null, explanation: 'The most iconic Mineiro food. Made with polvilho (tapioca starch) and queijo minas.', mineiro_note: 'Uai, pão de queijo é trem bão demais!', tags: '["food"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'coffee (small strong cup)', answer: 'cafezinho', distractors: null, explanation: 'Diminutive of café. Mineiros take their coffee strong and sweet.', mineiro_note: 'In Minas, offering cafezinho is a sign of hospitality.', tags: '["food"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'rice and beans (daily staple)', answer: 'arroz com feijão', distractors: null, explanation: 'The base of every Mineiro meal. Feijão in Minas is usually carioca (brown beans).', mineiro_note: null, tags: '["food"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'chicken (the meat)', answer: 'frango', distractors: null, explanation: 'Frango com quiabo (chicken with okra) is a classic Mineiro dish.', mineiro_note: null, tags: '["food"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'market / open-air market', answer: 'feira', distractors: null, explanation: 'Feiras are weekly open-air markets with fresh produce, cheese, and street food.', mineiro_note: 'In BH, the Mercado Central is the most famous feira.', tags: '["food","shopping"]', difficulty: 2 }),

  // === VOCAB: Mineiro Expressions ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '(interjection) surprise, emphasis, filler — uniquely Mineiro', answer: 'uai', distractors: null, explanation: 'The most iconic Mineiro word. Can express surprise, agreement, or be a conversation filler.', mineiro_note: 'Uai is to Mineiros what "like" is to Californians — everywhere.', tags: '["mineiro"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '"thing" or "stuff" (Mineiro replacement for coisa)', answer: 'trem', distractors: null, explanation: 'In standard BP, trem means train. In Minas, it means anything — object, situation, event.', mineiro_note: '"Esse trem tá bão" = "This thing is good"', tags: '["mineiro"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '"you" (informal Mineiro contraction of você)', answer: 'cê', distractors: null, explanation: 'Contracted form of você, used in casual Mineiro speech.', mineiro_note: '"Cê tá bão?" = "Você está bom?" (Are you good?)', tags: '["mineiro"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '"good" (Mineiro way to say bom)', answer: 'bão', distractors: null, explanation: 'Contracted form of bom. Used constantly in Minas Gerais.', mineiro_note: '"Bão demais da conta!" = "Really, really good!"', tags: '["mineiro"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '"wow!" (short for Nossa Senhora!)', answer: 'nó!', distractors: null, explanation: 'Exclamation of surprise, short for "Nossa Senhora!" (Our Lady!).', mineiro_note: '"Nó, que trem bonito!" = "Wow, what a beautiful thing!"', tags: '["mineiro"]', difficulty: 1 }),

  // === CLOZE: Ser vs Estar (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Eu ___ cansado. (I am tired — temporary state)', answer: 'estou', distractors: null, explanation: 'Use ESTAR for temporary states/feelings. "Estou cansado" = I am tired right now.', mineiro_note: 'Mineiro: "Cê tá cansado, sô?"', tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Ela ___ professora. (She is a teacher — profession)', answer: 'é', distractors: null, explanation: 'Use SER for professions, identity, permanent characteristics.', mineiro_note: null, tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Nós ___ em Belo Horizonte. (We are in BH — location)', answer: 'estamos', distractors: null, explanation: 'Use ESTAR for location. Where you ARE (estar) vs what you ARE (ser).', mineiro_note: 'BH = Belo Horizonte, capital of Minas Gerais.', tags: '["ser_estar"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'O café ___ quente. (The coffee is hot — current state)', answer: 'está', distractors: null, explanation: 'Use ESTAR for states that can change. The coffee is hot NOW but will cool.', mineiro_note: null, tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Minas Gerais ___ um estado grande. (MG is a big state — characteristic)', answer: 'é', distractors: null, explanation: 'Use SER for inherent characteristics. MG is permanently large.', mineiro_note: 'Minas Gerais is the 4th largest state in Brazil by area.', tags: '["ser_estar"]', difficulty: 2 }),

  // === CLOZE: Prepositions (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Eu moro ___ Belo Horizonte. (I live in BH)', answer: 'em', distractors: null, explanation: '"Morar em" = to live in. Portuguese uses "em" where Spanish uses "en".', mineiro_note: null, tags: '["preposition"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Vou ___ o mercado. (I\'m going to the market)', answer: 'ao', distractors: null, explanation: '"Ir ao" = to go to the (masculine). "ao" = a + o (contraction).', mineiro_note: null, tags: '["preposition"]', difficulty: 3 }),

  // === MULTIPLE CHOICE: False Cognates (A2) ===
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "esquisito" mean in Portuguese?', answer: 'strange/weird', distractors: '["exquisite","exclusive","essential"]', explanation: 'False cognate! Spanish "exquisito" = exquisite, but PT "esquisito" = strange/weird.', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "embaraçada" mean in Portuguese?', answer: 'pregnant', distractors: '["embarrassed","embraced","embedded"]', explanation: 'False cognate! Spanish "embarazada" = pregnant. PT "embaraçada" also = pregnant. "Embarrassed" in PT = "envergonhada".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "polvo" mean in Portuguese?', answer: 'octopus', distractors: '["dust","powder","chicken"]', explanation: 'False cognate! Spanish "polvo" = dust, but PT "polvo" = octopus. PT "dust" = "poeira".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),

  // === VOCAB: Greetings (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'good morning', answer: 'bom dia', distractors: null, explanation: 'Literally "good day". Used until around noon.', mineiro_note: null, tags: '["greetings"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'how are you? (informal)', answer: 'tudo bem?', distractors: null, explanation: 'Literally "everything good?" Most common informal greeting.', mineiro_note: 'Mineiro version: "Cê tá bão?"', tags: '["greetings"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'please', answer: 'por favor', distractors: null, explanation: 'Same structure as Spanish "por favor".', mineiro_note: null, tags: '["greetings"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'thank you (masculine speaker)', answer: 'obrigado', distractors: null, explanation: 'Men say "obrigado", women say "obrigada". Comes from "I am obliged".', mineiro_note: null, tags: '["greetings"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'excuse me / sorry', answer: 'com licença', distractors: null, explanation: '"Com licença" = excuse me (permission). "Desculpa" = sorry (apology).', mineiro_note: null, tags: '["greetings"]', difficulty: 2 }),

  // ============================================================
  // PHASE 2 CONTENT — IDs 28+ (do not reorder above this line)
  // ============================================================

  // === VOCAB: More Food (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'Minas cheese (soft white cheese)', answer: 'queijo minas', distractors: null, explanation: 'Soft, mild white cheese produced across Minas Gerais. UNESCO heritage.', mineiro_note: 'Queijo minas frescal with goiabada = "Romeu e Julieta"', tags: '["food"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'beans with cassava flour, eggs, and sausage', answer: 'feijão tropeiro', distractors: null, explanation: 'A hearty Mineiro dish originally made for tropeiros (mule drivers) traveling between towns.', mineiro_note: 'Trem mais bão da comida mineira!', tags: '["food"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'sweet made from milk (caramel spread)', answer: 'doce de leite', distractors: null, explanation: 'Slow-cooked sweetened milk. Similar to Argentine dulce de leche but thicker in Minas.', mineiro_note: null, tags: '["food"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'cornmeal porridge (Mineiro comfort food)', answer: 'angu', distractors: null, explanation: 'A thick cornmeal porridge, often served as a side dish with meats and beans.', mineiro_note: 'Angu com frango é comida de vó mineira.', tags: '["food"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'thick bean paste with cassava flour', answer: 'tutu de feijão', distractors: null, explanation: 'Mashed beans thickened with cassava flour. A signature Mineiro side dish.', mineiro_note: null, tags: '["food"]', difficulty: 3 }),

  // === VOCAB: Travel & Directions (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'airport', answer: 'aeroporto', distractors: null, explanation: 'BH has two airports: Confins (international) and Pampulha (domestic).', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'ticket (for bus or plane)', answer: 'passagem', distractors: null, explanation: '"Passagem" = ticket for transport. "Ingresso" = ticket for events.', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'map', answer: 'mapa', distractors: null, explanation: 'Masculine noun: "o mapa" (not "a mapa"). One of Portuguese\'s irregular genders.', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'bus station', answer: 'rodoviária', distractors: null, explanation: 'Long-distance bus station. City buses use "ponto de ônibus" (bus stop).', mineiro_note: 'BH rodoviária is in the city center, near Praça Rio Branco.', tags: '["travel"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'corner (of a street)', answer: 'esquina', distractors: null, explanation: '"Na esquina" = on the corner. Used constantly in directions.', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'street', answer: 'rua', distractors: null, explanation: 'Common noun. "Rua" is smaller than "avenida" (avenue).', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'avenue (wide road)', answer: 'avenida', distractors: null, explanation: 'Wider than "rua". Avenida Afonso Pena is BH\'s main avenue.', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'traffic light', answer: 'semáforo', distractors: null, explanation: 'Also called "sinal" in casual speech. "O sinal tá vermelho" = the light is red.', mineiro_note: null, tags: '["travel"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'bridge', answer: 'ponte', distractors: null, explanation: 'Feminine noun: "a ponte".', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'highway / road', answer: 'estrada', distractors: null, explanation: '"Estrada" = road/highway (general). "Rodovia" = numbered highway.', mineiro_note: 'Minas has beautiful estradas through the Serra da Mantiqueira.', tags: '["travel"]', difficulty: 2 }),

  // === VOCAB: Family (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'mother', answer: 'mãe', distractors: null, explanation: 'Informal: "mamãe". The ã nasal sound is key in Portuguese.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'father', answer: 'pai', distractors: null, explanation: 'Informal: "papai". Plural "pais" = parents.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'brother', answer: 'irmão', distractors: null, explanation: 'Feminine: "irmã". Plural: "irmãos" (siblings).', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'sister', answer: 'irmã', distractors: null, explanation: 'Note the nasal ã. Mineiros sometimes say "minha irmã" very quickly: "minhirmã".', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'grandfather', answer: 'avô', distractors: null, explanation: 'Closed ô sound. "Avó" (grandmother) has open ó sound. The accent matters!', mineiro_note: null, tags: '["family"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'grandmother', answer: 'avó', distractors: null, explanation: 'Open ó sound. Informal: "vovó". Mineiro grandmothers are legendary cooks.', mineiro_note: 'Comida de vó mineira é o melhor trem do mundo!', tags: '["family"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'cousin (male)', answer: 'primo', distractors: null, explanation: 'Female cousin: "prima". Same as Spanish.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'uncle', answer: 'tio', distractors: null, explanation: '"Tio" is also used informally to address older men you respect.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'aunt', answer: 'tia', distractors: null, explanation: '"Tia" is also used for female teachers by young children.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'mother-in-law', answer: 'sogra', distractors: null, explanation: '"Sogro" = father-in-law. Brazilian culture has lots of sogra jokes!', mineiro_note: null, tags: '["family"]', difficulty: 2 }),

  // === VOCAB: Daily Routine (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to wake up', answer: 'acordar', distractors: null, explanation: 'False cognate alert! Spanish "acordar" = to agree/remember. PT "acordar" = to wake up.', mineiro_note: null, tags: '["daily_routine","false_cognate"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to brush teeth', answer: 'escovar os dentes', distractors: null, explanation: '"Escovar" = to brush. "Escova de dentes" = toothbrush.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to take a shower', answer: 'tomar banho', distractors: null, explanation: '"Tomar" here means "to take". Brazilians shower 2-3 times daily in hot weather.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'breakfast', answer: 'café da manhã', distractors: null, explanation: 'Literally "morning coffee". In Minas, breakfast is a lavish spread with cheese bread, cakes, and fruit.', mineiro_note: 'Café da manhã mineiro é famoso — queijo, pão de queijo, bolo, biscoito...', tags: '["daily_routine","food"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'lunch', answer: 'almoço', distractors: null, explanation: 'The main meal in Brazil, usually around noon-1pm. "Almoçar" = to have lunch.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'dinner', answer: 'jantar', distractors: null, explanation: 'Also the verb: "jantar" = to have dinner. Usually lighter than lunch.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to sleep', answer: 'dormir', distractors: null, explanation: 'Same as Spanish. "Estou com sono" = I\'m sleepy.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to work', answer: 'trabalhar', distractors: null, explanation: '"Trabalho" = work (noun). Similar to Spanish "trabajar".', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to rest', answer: 'descansar', distractors: null, explanation: 'Same as Spanish "descansar". "Preciso descansar" = I need to rest.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to cook', answer: 'cozinhar', distractors: null, explanation: '"Cozinha" = kitchen. Mineiros are proud of their cooking traditions.', mineiro_note: 'Cozinha mineira é patrimônio cultural!', tags: '["daily_routine"]', difficulty: 1 }),

  // === VOCAB: Body & Health (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'head', answer: 'cabeça', distractors: null, explanation: '"Dor de cabeça" = headache. Note the ç (cedilla).', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'arm', answer: 'braço', distractors: null, explanation: 'Note the ç. Plural: "braços".', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'leg', answer: 'perna', distractors: null, explanation: '"Perna" in Portuguese. Similar to Spanish "pierna".', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'stomachache', answer: 'dor de barriga', distractors: null, explanation: '"Barriga" = belly/stomach. "Dor" = pain.', mineiro_note: null, tags: '["body_health"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'fever', answer: 'febre', distractors: null, explanation: '"Estar com febre" = to have a fever. Uses ESTAR (temporary state).', mineiro_note: null, tags: '["body_health","ser_estar"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'medicine / remedy', answer: 'remédio', distractors: null, explanation: '"Tomar remédio" = to take medicine. "Remédio" is more common than "medicamento" in casual speech.', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'doctor\'s appointment', answer: 'consulta', distractors: null, explanation: '"Marcar uma consulta" = to schedule an appointment. Not to be confused with Spanish "consulta" (question).', mineiro_note: null, tags: '["body_health"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'hospital', answer: 'hospital', distractors: null, explanation: 'Same word, different pronunciation: stress on last syllable (hos-pi-TAL).', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'pharmacy', answer: 'farmácia', distractors: null, explanation: 'Also called "drogaria" for larger chain pharmacies in Brazil.', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'flu / cold', answer: 'gripe', distractors: null, explanation: '"Estar gripado" = to have the flu. Very common expression.', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),

  // === VOCAB: Emotions (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'happy', answer: 'feliz', distractors: null, explanation: 'Same for masculine and feminine. "Estou feliz" (uses ESTAR — current feeling).', mineiro_note: null, tags: '["emotions","ser_estar"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'sad', answer: 'triste', distractors: null, explanation: 'Same for both genders. "Estou triste" = I am sad (right now).', mineiro_note: null, tags: '["emotions"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'worried', answer: 'preocupado', distractors: null, explanation: 'Feminine: "preocupada". "Estou preocupado com..." = I\'m worried about...', mineiro_note: null, tags: '["emotions"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'excited / lively', answer: 'animado', distractors: null, explanation: '"Animado" in PT = excited/enthusiastic. NOT "animated" like in English.', mineiro_note: null, tags: '["emotions"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'missing someone / nostalgia (untranslatable)', answer: 'saudade', distractors: null, explanation: 'One of the most famous Portuguese words — a deep longing for something or someone absent. No direct English equivalent.', mineiro_note: 'Saudade is the soul of Portuguese music and poetry.', tags: '["emotions"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'nervous', answer: 'nervoso', distractors: null, explanation: 'Feminine: "nervosa". Can also mean angry in casual usage.', mineiro_note: null, tags: '["emotions"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'calm / chill', answer: 'tranquilo', distractors: null, explanation: '"Tranquilo" is used constantly in Brazil — as a response ("tá tranquilo" = it\'s all good), as reassurance.', mineiro_note: '"Fica tranquilo, sô!" = "Relax, dude!"', tags: '["emotions"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'proud', answer: 'orgulhoso', distractors: null, explanation: 'Feminine: "orgulhosa". "Tenho orgulho de..." = I\'m proud of...', mineiro_note: null, tags: '["emotions"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'embarrassed / ashamed', answer: 'envergonhado', distractors: null, explanation: 'This is the real "embarrassed" in PT — NOT "embaraçada" (which means pregnant).', mineiro_note: null, tags: '["emotions","false_cognate"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'tired', answer: 'cansado', distractors: null, explanation: 'Uses ESTAR: "Estou cansado" (temporary state, not identity).', mineiro_note: null, tags: '["emotions","ser_estar"]', difficulty: 1 }),

  // === VOCAB: Shopping (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'price', answer: 'preço', distractors: null, explanation: '"Qual é o preço?" = What\'s the price? Note the ç.', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'discount', answer: 'desconto', distractors: null, explanation: '"Tem desconto?" = Is there a discount? A must-know phrase for Brazilian markets.', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'expensive', answer: 'caro', distractors: null, explanation: 'Feminine: "cara". "Tá caro demais!" = It\'s too expensive!', mineiro_note: 'Mineiro: "Nó, que trem caro!"', tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'cheap / inexpensive', answer: 'barato', distractors: null, explanation: 'Feminine: "barata". But "barata" also means cockroach — context matters!', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'change (money returned)', answer: 'troco', distractors: null, explanation: '"Tem troco?" = Do you have change? Very common in small shops.', mineiro_note: null, tags: '["shopping"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'card (credit/debit)', answer: 'cartão', distractors: null, explanation: '"Aceita cartão?" = Do you accept card? Essential phrase.', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'cash / money', answer: 'dinheiro', distractors: null, explanation: '"Pagar em dinheiro" = to pay in cash. Pix is now more common than cash in Brazil.', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'bag (shopping bag)', answer: 'sacola', distractors: null, explanation: '"Sacola" = shopping/plastic bag. "Bolsa" = purse/handbag.', mineiro_note: null, tags: '["shopping"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'to try on (clothing)', answer: 'provar', distractors: null, explanation: '"Posso provar?" = Can I try it on? "Provador" = fitting room.', mineiro_note: null, tags: '["shopping"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'size (clothing)', answer: 'tamanho', distractors: null, explanation: '"Que tamanho você usa?" = What size do you wear?', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),

  // === VOCAB: Work (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'office', answer: 'escritório', distractors: null, explanation: 'Note the accent. "Trabalho no escritório" = I work in the office.', mineiro_note: null, tags: '["work"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'meeting', answer: 'reunião', distractors: null, explanation: '"Ter uma reunião" = to have a meeting. The ã nasal is important.', mineiro_note: null, tags: '["work"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'boss', answer: 'chefe', distractors: null, explanation: 'Same for male and female. Can also mean "chef" in a kitchen context.', mineiro_note: null, tags: '["work"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'colleague / coworker', answer: 'colega', distractors: null, explanation: '"Colega de trabalho" = work colleague. Gender-neutral noun.', mineiro_note: null, tags: '["work"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'salary', answer: 'salário', distractors: null, explanation: 'Similar to Spanish "salario". "Salário mínimo" = minimum wage.', mineiro_note: null, tags: '["work"]', difficulty: 1 }),

  // === CLOZE: More Ser vs Estar (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Eu ___ de Minas Gerais. (I am from MG — origin)', answer: 'sou', distractors: null, explanation: 'Use SER for origin/nationality. "Sou mineiro" = I am from Minas.', mineiro_note: '"Sou mineiro, uai!" — with pride!', tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'O tempo ___ frio hoje. (The weather is cold today — current)', answer: 'está', distractors: null, explanation: 'Use ESTAR for weather (temporary condition). "Está chovendo" = It is raining.', mineiro_note: null, tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'A festa ___ amanhã. (The party is tomorrow — scheduled event)', answer: 'é', distractors: null, explanation: 'Use SER for scheduled events, dates, and times. "A reunião é às 3" = The meeting is at 3.', mineiro_note: null, tags: '["ser_estar"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Ela ___ muito bonita hoje. (She looks very pretty today — temporary)', answer: 'está', distractors: null, explanation: 'ESTAR + bonita = looks pretty today (implies she doesn\'t always). SER + bonita = IS pretty (inherently).', mineiro_note: 'Subtle difference! "Ela é bonita" vs "Ela está bonita" changes meaning.', tags: '["ser_estar"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Nós ___ amigos. (We are friends — relationship)', answer: 'somos', distractors: null, explanation: 'Use SER for relationships. "Somos amigos" = We are friends (ongoing relationship).', mineiro_note: null, tags: '["ser_estar"]', difficulty: 2 }),

  // === CLOZE: Present Tense Verbs (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ português todos os dias. (I study Portuguese every day — estudar)', answer: 'estudo', distractors: null, explanation: 'Regular -ar verb. Eu estudo, você estuda, nós estudamos.', mineiro_note: null, tags: '["verbs"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Ela ___ água. (She drinks water — beber)', answer: 'bebe', distractors: null, explanation: 'Regular -er verb. Eu bebo, você bebe, nós bebemos.', mineiro_note: null, tags: '["verbs"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Nós ___ no centro. (We live downtown — morar)', answer: 'moramos', distractors: null, explanation: 'Regular -ar verb. "Morar" = to live (reside). "Nós moramos" = we live.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ pão de queijo. (I want cheese bread — querer)', answer: 'quero', distractors: null, explanation: 'Irregular verb. Eu quero, você quer, nós queremos. Very common in daily speech.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eles ___ inglês e português. (They speak English and Portuguese — falar)', answer: 'falam', distractors: null, explanation: 'Regular -ar verb. "Eles falam" = they speak. In Mineiro casual speech: "falano" (dropping the d from gerund).', mineiro_note: 'Mineiro gerund: "tô falano" instead of "tô falando"', tags: '["verbs","mineiro"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ ao mercado. (I go to the market — ir)', answer: 'vou', distractors: null, explanation: 'Irregular verb "ir". Eu vou, você vai, nós vamos. "Vamos!" = Let\'s go!', mineiro_note: null, tags: '["verbs"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Você ___ onde fica o mercado? (Do you know where the market is? — saber)', answer: 'sabe', distractors: null, explanation: 'Irregular verb "saber" (to know facts). "Conhecer" = to know (be familiar with). Important distinction!', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ que a comida mineira é boa. (I think/find that Mineiro food is good — achar)', answer: 'acho', distractors: null, explanation: '"Achar" = to think/find (opinion) or to find (physically). "Eu acho que sim" = I think so.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Nós ___ café toda manhã. (We have/drink coffee every morning — tomar)', answer: 'tomamos', distractors: null, explanation: '"Tomar" = to take/have (drinks/meals). "Tomar café" = to drink coffee or to have breakfast.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ que você é mineiro. (I know/can tell you are Mineiro — perceber)', answer: 'percebo', distractors: null, explanation: '"Perceber" = to perceive/notice. NOT "to perceive" as suspect — that\'s more neutral in PT.', mineiro_note: null, tags: '["verbs"]', difficulty: 3 }),

  // === CLOZE: Past Tense Verbs (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Ontem eu ___ pão de queijo. (Yesterday I ate cheese bread — comer)', answer: 'comi', distractors: null, explanation: 'Preterite of "comer". Eu comi, você comeu, nós comemos.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Ela ___ com a mãe dela. (She spoke with her mother — falar)', answer: 'falou', distractors: null, explanation: 'Preterite of "falar". Eu falei, você falou, nós falamos.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Nós ___ para Ouro Preto. (We went to Ouro Preto — ir)', answer: 'fomos', distractors: null, explanation: 'Irregular preterite of "ir". Eu fui, você foi, nós fomos. Same forms as "ser" in preterite!', mineiro_note: 'Ouro Preto is a UNESCO World Heritage colonial town in Minas.', tags: '["verbs"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eu ___ um café. (I had/drank a coffee — tomar)', answer: 'tomei', distractors: null, explanation: 'Preterite of "tomar". Eu tomei, você tomou, nós tomamos.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Ele ___ no hospital. (He was at the hospital — estar)', answer: 'esteve', distractors: null, explanation: 'Irregular preterite of "estar". Eu estive, você esteve, nós estivemos.', mineiro_note: null, tags: '["verbs","ser_estar"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eu ___ muito ontem. (I studied a lot yesterday — estudar)', answer: 'estudei', distractors: null, explanation: 'Regular -ar preterite. Eu estudei, você estudou, nós estudamos.', mineiro_note: null, tags: '["verbs"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Você ___ o filme? (Did you watch the movie? — assistir)', answer: 'assistiu', distractors: null, explanation: 'Regular -ir preterite. "Assistir" in PT requires "a": "Assistir ao filme". But colloquially the "a" is often dropped.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eu ___ um presente para ela. (I bought a gift for her — comprar)', answer: 'comprei', distractors: null, explanation: 'Regular -ar preterite. Eu comprei, você comprou, nós compramos.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eles ___ muito cedo. (They arrived very early — chegar)', answer: 'chegaram', distractors: null, explanation: 'Regular -ar preterite (3rd plural). Note: "chegar" uses "em" not "a" for arrival: "Chegaram em casa".', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eu não ___ nada. (I didn\'t do anything — fazer)', answer: 'fiz', distractors: null, explanation: 'Irregular preterite of "fazer". Eu fiz, você fez, nós fizemos. Very common verb!', mineiro_note: null, tags: '["verbs"]', difficulty: 3 }),

  // === CLOZE: More Prepositions (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'O café ___ Maria é bom. (Maria\'s coffee — possession)', answer: 'da', distractors: null, explanation: '"Da" = de + a (of the, feminine). "Do" = de + o (masculine).', mineiro_note: null, tags: '["preposition"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Isso é ___ você. (This is for you)', answer: 'para', distractors: null, explanation: '"Para" = for/to. Often shortened to "pra" in casual speech.', mineiro_note: 'Mineiro: "Isso é pra cê"', tags: '["preposition"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Ele passou ___ a porta. (He passed through the door)', answer: 'pela', distractors: null, explanation: '"Pela" = por + a. "Pelo" = por + o. Contractions with "por" (by/through).', mineiro_note: null, tags: '["preposition"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Vou ___ você. (I\'m going with you)', answer: 'com', distractors: null, explanation: '"Com" = with. "Comigo" = with me, "contigo" = with you (formal).', mineiro_note: null, tags: '["preposition"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Saí ___ dinheiro. (I left without money)', answer: 'sem', distractors: null, explanation: '"Sem" = without. Opposite of "com". "Sem problema" = no problem.', mineiro_note: null, tags: '["preposition"]', difficulty: 1 }),

  // === MULTIPLE CHOICE: More False Cognates (A2) ===
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "acordar" mean in Portuguese?', answer: 'to wake up', distractors: '["to agree","to record","to remember"]', explanation: 'False cognate! Spanish "acordar" = to agree/remember. PT "acordar" = to wake up. PT "agree" = "concordar".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "borracha" mean in Portuguese?', answer: 'eraser / rubber', distractors: '["drunk woman","bottle","rubber band"]', explanation: 'False cognate! Spanish "borracha" = drunk woman. PT "borracha" = eraser/rubber. PT "drunk" = "bêbada".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "pasta" mean in Portuguese?', answer: 'folder / briefcase', distractors: '["pasta (food)","paste","dough"]', explanation: 'False cognate! PT "pasta" = folder/briefcase. PT pasta (food) = "massa" or "macarrão".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "puxar" mean in Portuguese?', answer: 'to pull', distractors: '["to push","to punch","to rush"]', explanation: '"Puxar" = to pull. Looks like "push" but means the opposite! PT "push" = "empurrar".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "largo" mean in Portuguese?', answer: 'wide / public square', distractors: '["long","large","far"]', explanation: 'PT "largo" = wide or a public square. PT "long" = "longo". PT "large" = "grande".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),

  // === MULTIPLE CHOICE: Mineiro vs Standard BP (A2) ===
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'What is the standard BP equivalent of "Cê tá bão?"', answer: 'Você está bom?', distractors: '["Você é bom?","Você tem bom?","Você fica bom?"]', explanation: '"Cê" = você, "tá" = está, "bão" = bom. Classic Mineiro contraction.', mineiro_note: 'This is THE Mineiro greeting. You\'ll hear it dozens of times a day.', tags: '["mineiro"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'What does "Ô sô, cê viu aquele trem?" mean?', answer: 'Hey dude, did you see that thing?', distractors: '["Oh sir, you saw that train?","Hey you, did you watch that show?","Oh dear, you lost your thing?"]', explanation: '"Sô" = dude (vocative), "cê" = you, "viu" = saw, "trem" = thing (not train!).', mineiro_note: null, tags: '["mineiro"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'In Mineiro speech, how would you say "falando" (speaking)?', answer: 'falano', distractors: '["falando","falanho","falão"]', explanation: 'Mineiros drop the "d" from gerunds: falando→falano, comendo→comeno, fazendo→fazeno.', mineiro_note: 'This is one of the most distinctive Mineiro speech patterns.', tags: '["mineiro"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'What does "Nó!" express in Mineiro?', answer: 'Surprise or amazement (like "wow!")', distractors: '["A knot","No / denial","A problem"]', explanation: '"Nó" is short for "Nossa Senhora!" (Our Lady!). Used to express surprise, amazement, or shock.', mineiro_note: '"Nó, que trem bão!" = "Wow, what a great thing!"', tags: '["mineiro"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'What does "uai" typically express?', answer: 'Surprise, agreement, or used as a filler word', distractors: '["Sadness","Anger","A question"]', explanation: '"Uai" is the most versatile Mineiro word — surprise, emphasis, agreement, or just filler. Like "like" in California English.', mineiro_note: null, tags: '["mineiro"]', difficulty: 1 }),

  // === MULTIPLE CHOICE: Cultural Knowledge (A2) ===
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What is the capital of Minas Gerais?', answer: 'Belo Horizonte', distractors: '["São Paulo","Ouro Preto","Tiradentes"]', explanation: 'Belo Horizonte (BH) became the capital in 1897, replacing Ouro Preto. It\'s Brazil\'s 3rd largest metro area.', mineiro_note: null, tags: '["cultural"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What does "Minas Gerais" literally mean?', answer: 'General Mines', distractors: '["My Generals","Mining Town","Beautiful Mountains"]', explanation: 'Named for the abundant gold and gemstone mines discovered in the 18th century. "Minas" = mines, "Gerais" = general.', mineiro_note: null, tags: '["cultural"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What is "pão de queijo" made from?', answer: 'Tapioca starch (polvilho) and cheese', distractors: '["Wheat flour and cheese","Cornmeal and milk","Rice flour and butter"]', explanation: 'Polvilho (tapioca/cassava starch) gives pão de queijo its unique chewy texture. Wheat flour is never used.', mineiro_note: null, tags: '["cultural","food"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What is Ouro Preto famous for?', answer: 'Colonial baroque architecture and gold mining history', distractors: '["Beaches and surfing","Modern skyscrapers","Coffee plantations"]', explanation: 'Ouro Preto is a UNESCO World Heritage Site, the heart of Brazil\'s 18th-century gold rush. "Ouro" = gold, "Preto" = black.', mineiro_note: null, tags: '["cultural"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What is a "boteco" in Minas?', answer: 'A casual bar / neighborhood pub', distractors: '["A type of cheese","A dance style","A traditional hat"]', explanation: '"Boteco" (or "buteco") is a casual neighborhood bar serving beer, cachaça, and petiscos (snacks). Central to Mineiro social life.', mineiro_note: 'BH has an annual "Comida di Buteco" festival — a boteco food competition!', tags: '["cultural"]', difficulty: 2 }),

  // === ERROR CORRECTION (A2) ===
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu sou cansado.', answer: 'Eu estou cansado.', distractors: null, explanation: '"Tired" is a temporary state → use ESTAR, not SER. "Sou cansado" would mean you ARE a tired person by nature.', mineiro_note: null, tags: '["ser_estar","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Ela é em Belo Horizonte.', answer: 'Ela está em Belo Horizonte.', distractors: null, explanation: 'Location uses ESTAR, not SER. "Ela é de BH" (origin) vs "Ela está em BH" (current location).', mineiro_note: null, tags: '["ser_estar","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu moro a Belo Horizonte.', answer: 'Eu moro em Belo Horizonte.', distractors: null, explanation: '"Morar" takes the preposition "em" (in), not "a". Spanish uses "en" similarly.', mineiro_note: null, tags: '["preposition","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'O polvo é muito bom para limpar.', answer: 'A poeira é muito boa para limpar.', distractors: null, explanation: '"Polvo" = octopus, not dust! Dust = "poeira". And "poeira" is feminine → "boa", not "bom".', mineiro_note: null, tags: '["false_cognate","error_correction"]', difficulty: 3 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu estou embaraçado.', answer: 'Eu estou envergonhado.', distractors: null, explanation: '"Embaraçado" means pregnant (for women) or tangled, NOT embarrassed. Use "envergonhado" for embarrassed.', mineiro_note: null, tags: '["false_cognate","error_correction"]', difficulty: 3 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'A menina bonito chegou.', answer: 'A menina bonita chegou.', distractors: null, explanation: 'Gender agreement: "menina" (girl) is feminine → "bonita" (not "bonito"). Adjectives must match the noun\'s gender.', mineiro_note: null, tags: '["grammar","error_correction"]', difficulty: 1 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu vou ao mercado para comprar leites.', answer: 'Eu vou ao mercado para comprar leite.', distractors: null, explanation: '"Leite" (milk) is uncountable — no plural. "Comprar leite" not "leites". For bottles: "garrafas de leite".', mineiro_note: null, tags: '["grammar","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu gosto de ela.', answer: 'Eu gosto dela.', distractors: null, explanation: '"De" + "ela" contracts to "dela". Portuguese prepositions always contract with pronouns: dele, dela, deles, delas.', mineiro_note: null, tags: '["grammar","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu tenho vinte e um anos.', answer: 'Eu tenho vinte e um anos.', distractors: null, explanation: 'Trick question! This sentence is correct. Portuguese uses "ter" (to have) for age, just like Spanish. NOT "ser" like in English.', mineiro_note: null, tags: '["grammar","error_correction"]', difficulty: 1 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu puxei a porta para abrir.', answer: 'Eu empurrei a porta para abrir.', distractors: null, explanation: '"Puxar" = to PULL, not push! If you\'re opening a door by pushing, use "empurrar". Classic false friend with English "push".', mineiro_note: null, tags: '["false_cognate","error_correction"]', difficulty: 2 }),

  // === B1 CONTENT ===
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'emotions', prompt: 'to miss (feel saudade for someone)', answer: 'sentir falta', distractors: null, explanation: '"Sinto falta de você" = I miss you. More specific than "saudade" — focuses on the absence.', mineiro_note: null, tags: '["emotions","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'work', prompt: 'to resign / quit a job', answer: 'pedir demissão', distractors: null, explanation: '"Pedir" = to ask for, "demissão" = dismissal. You ASK FOR your own dismissal. "Ser demitido" = to be fired.', mineiro_note: null, tags: '["work","B1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'daily_routine', prompt: 'to be running late', answer: 'estar atrasado', distractors: null, explanation: '"Atrasado" = late/delayed. Uses ESTAR (temporary state). "Desculpa, estou atrasado" = Sorry, I\'m running late.', mineiro_note: null, tags: '["daily_routine","ser_estar","B1"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'verbs_present', prompt: 'Se eu ___ dinheiro, eu viajava. (If I had money, I would travel — ter, imperfect subjunctive)', answer: 'tivesse', distractors: null, explanation: 'Imperfect subjunctive of "ter". Used in hypothetical/conditional sentences: "Se eu tivesse..."', mineiro_note: null, tags: '["verbs","subjunctive","B1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'verbs_present', prompt: 'Espero que você ___ bem. (I hope you are well — estar, present subjunctive)', answer: 'esteja', distractors: null, explanation: 'Present subjunctive of "estar". After "espero que" (I hope that), use subjunctive.', mineiro_note: null, tags: '["verbs","subjunctive","B1"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'cultural', prompt: 'What is "Inconfidência Mineira"?', answer: 'An 18th-century independence movement in Minas Gerais', distractors: '["A type of Mineiro music","A colonial church in Ouro Preto","A traditional festival"]', explanation: 'The 1789 conspiracy against Portuguese colonial rule, led by Tiradentes (Joaquim José da Silva Xavier). He was executed and became a national hero.', mineiro_note: 'Tiradentes is a national holiday (April 21) and a beautiful colonial town in Minas.', tags: '["cultural","B1"]', difficulty: 3 }),
];
