/**
 * Hardcoded seed content for Phase 1.
 * This replaces the Python content generation pipeline for now —
 * enough exercises to practice for 2 weeks.
 *
 * In Phase 4, this will be replaced by SQLite content DB (fluent.db).
 */

import type { Exercise } from './exercises';

let nextId = 1;
function ex(partial: Omit<Exercise, 'id'>): Exercise {
  return { id: nextId++, ...partial };
}

export const SEED_EXERCISES: Exercise[] = [
  // === VOCAB: Food (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'bread (the round cheese bread from Minas)', answer: 'pão de queijo', distractors: null, explanation: 'The most iconic Mineiro food. Made with polvilho (tapioca starch) and queijo minas.', mineiro_note: 'Uai, pão de queijo é trem bão demais!', tags: '["food"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'coffee (small strong cup)', answer: 'cafezinho', distractors: null, explanation: 'Diminutive of café. Mineiros take their coffee strong and sweet.', mineiro_note: 'In Minas, offering cafezinho is a sign of hospitality.', tags: '["food"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'rice and beans (daily staple)', answer: 'arroz com feijão', distractors: null, explanation: 'The base of every Mineiro meal. Feijão in Minas is usually carioca (brown beans).', mineiro_note: null, tags: '["food"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'chicken (the meat)', answer: 'frango', distractors: null, explanation: 'Frango com quiabo (chicken with okra) is a classic Mineiro dish.', mineiro_note: null, tags: '["food"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'market / open-air market', answer: 'feira', distractors: null, explanation: 'Feiras are weekly open-air markets with fresh produce, cheese, and street food.', mineiro_note: 'In BH, the Mercado Central is the most famous feira.', tags: '["food","shopping"]', difficulty: 2 }),

  // === VOCAB: Mineiro Expressions ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '(interjection) surprise, emphasis, filler — uniquely Mineiro', answer: 'uai', distractors: null, explanation: 'The most iconic Mineiro word. Can express surprise, agreement, or be a conversation filler.', mineiro_note: 'Uai is to Mineiros what "like" is to Californians — everywhere.', tags: '["mineiro"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '"thing" or "stuff" (Mineiro replacement for coisa)', answer: 'trem', distractors: null, explanation: 'In standard BP, trem means train. In Minas, it means anything — object, situation, event.', mineiro_note: '"Esse trem tá bão" = "This thing is good"', tags: '["mineiro"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '"you" (informal Mineiro contraction of você)', answer: 'cê', distractors: null, explanation: 'Contracted form of você, used in casual Mineiro speech.', mineiro_note: '"Cê tá bão?" = "Você está bom?" (Are you good?)', tags: '["mineiro"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '"good" (Mineiro way to say bom)', answer: 'bão', distractors: null, explanation: 'Contracted form of bom. Used constantly in Minas Gerais.', mineiro_note: '"Bão demais da conta!" = "Really, really good!"', tags: '["mineiro"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'mineiro', prompt: '"wow!" (short for Nossa Senhora!)', answer: 'nó!', distractors: null, explanation: 'Exclamation of surprise, short for "Nossa Senhora!" (Our Lady!).', mineiro_note: '"Nó, que trem bonito!" = "Wow, what a beautiful thing!"', tags: '["mineiro"]', difficulty: 1 }),

  // === CLOZE: Ser vs Estar (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Eu ___ cansado. (I am tired — temporary state)', answer: 'estou', distractors: null, explanation: 'Use ESTAR for temporary states/feelings. "Estou cansado" = I am tired right now.', mineiro_note: 'Mineiro: "Cê tá cansado, sô?"', tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Ela ___ professora. (She is a teacher — profession)', answer: 'é', distractors: null, explanation: 'Use SER for professions, identity, permanent characteristics.', mineiro_note: null, tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Nós ___ em Belo Horizonte. (We are in BH — location)', answer: 'estamos', distractors: null, explanation: 'Use ESTAR for location. Where you ARE (estar) vs what you ARE (ser).', mineiro_note: 'BH = Belo Horizonte, capital of Minas Gerais.', tags: '["ser_estar"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'O café ___ quente. (The coffee is hot — current state)', answer: 'está', distractors: null, explanation: 'Use ESTAR for states that can change. The coffee is hot NOW but will cool.', mineiro_note: null, tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Minas Gerais ___ um estado grande. (MG is a big state — characteristic)', answer: 'é', distractors: null, explanation: 'Use SER for inherent characteristics. MG is permanently large.', mineiro_note: 'Minas Gerais is the 4th largest state in Brazil by area.', tags: '["ser_estar"]', difficulty: 2 }),

  // === CLOZE: Prepositions (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Eu moro ___ Belo Horizonte. (I live in BH)', answer: 'em', distractors: null, explanation: '"Morar em" = to live in. Portuguese uses "em" where Spanish uses "en".', mineiro_note: null, tags: '["preposition"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Vou ___ o mercado. (I\'m going to the market)', answer: 'ao', distractors: null, explanation: '"Ir ao" = to go to the (masculine). "ao" = a + o (contraction).', mineiro_note: null, tags: '["preposition"]', difficulty: 3 }),

  // === MULTIPLE CHOICE: False Cognates (A2) ===
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "esquisito" mean in Portuguese?', answer: 'strange/weird', distractors: '["exquisite","exclusive","essential"]', explanation: 'False cognate! Spanish "exquisito" = exquisite, but PT "esquisito" = strange/weird.', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "embaraçada" mean in Portuguese?', answer: 'pregnant', distractors: '["embarrassed","embraced","embedded"]', explanation: 'False cognate! Spanish "embarazada" = pregnant. PT "embaraçada" also = pregnant. "Embarrassed" in PT = "envergonhada".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "polvo" mean in Portuguese?', answer: 'octopus', distractors: '["dust","powder","chicken"]', explanation: 'False cognate! Spanish "polvo" = dust, but PT "polvo" = octopus. PT "dust" = "poeira".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),

  // === VOCAB: Greetings (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'good morning', answer: 'bom dia', distractors: null, explanation: 'Literally "good day". Used until around noon.', mineiro_note: null, tags: '["greetings"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'how are you? (informal)', answer: 'tudo bem?', distractors: null, explanation: 'Literally "everything good?" Most common informal greeting.', mineiro_note: 'Mineiro version: "Cê tá bão?"', tags: '["greetings"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'please', answer: 'por favor', distractors: null, explanation: 'Same structure as Spanish "por favor".', mineiro_note: null, tags: '["greetings"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'thank you (masculine speaker)', answer: 'obrigado', distractors: null, explanation: 'Men say "obrigado", women say "obrigada". Comes from "I am obliged".', mineiro_note: null, tags: '["greetings"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'greetings', prompt: 'excuse me / sorry', answer: 'com licença', distractors: null, explanation: '"Com licença" = excuse me (permission). "Desculpa" = sorry (apology).', mineiro_note: null, tags: '["greetings"]', difficulty: 2 }),

  // ============================================================
  // PHASE 2 CONTENT — IDs 28+ (do not reorder above this line)
  // ============================================================

  // === VOCAB: More Food (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'Minas cheese (soft white cheese)', answer: 'queijo minas', distractors: null, explanation: 'Soft, mild white cheese produced across Minas Gerais. UNESCO heritage.', mineiro_note: 'Queijo minas frescal with goiabada = "Romeu e Julieta"', tags: '["food"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'beans with cassava flour, eggs, and sausage', answer: 'feijão tropeiro', distractors: null, explanation: 'A hearty Mineiro dish originally made for tropeiros (mule drivers) traveling between towns.', mineiro_note: 'Trem mais bão da comida mineira!', tags: '["food"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'sweet made from milk (caramel spread)', answer: 'doce de leite', distractors: null, explanation: 'Slow-cooked sweetened milk. Similar to Argentine dulce de leche but thicker in Minas.', mineiro_note: null, tags: '["food"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'cornmeal porridge (Mineiro comfort food)', answer: 'angu', distractors: null, explanation: 'A thick cornmeal porridge, often served as a side dish with meats and beans.', mineiro_note: 'Angu com frango é comida de vó mineira.', tags: '["food"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'food', prompt: 'thick bean paste with cassava flour', answer: 'tutu de feijão', distractors: null, explanation: 'Mashed beans thickened with cassava flour. A signature Mineiro side dish.', mineiro_note: null, tags: '["food"]', difficulty: 3 }),

  // === VOCAB: Travel & Directions (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'airport', answer: 'aeroporto', distractors: null, explanation: 'BH has two airports: Confins (international) and Pampulha (domestic).', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'ticket (for bus or plane)', answer: 'passagem', distractors: null, explanation: '"Passagem" = ticket for transport. "Ingresso" = ticket for events.', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'map', answer: 'mapa', distractors: null, explanation: 'Masculine noun: "o mapa" (not "a mapa"). One of Portuguese\'s irregular genders.', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'bus station', answer: 'rodoviária', distractors: null, explanation: 'Long-distance bus station. City buses use "ponto de ônibus" (bus stop).', mineiro_note: 'BH rodoviária is in the city center, near Praça Rio Branco.', tags: '["travel"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'corner (of a street)', answer: 'esquina', distractors: null, explanation: '"Na esquina" = on the corner. Used constantly in directions.', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'street', answer: 'rua', distractors: null, explanation: 'Common noun. "Rua" is smaller than "avenida" (avenue).', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'avenue (wide road)', answer: 'avenida', distractors: null, explanation: 'Wider than "rua". Avenida Afonso Pena is BH\'s main avenue.', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'traffic light', answer: 'semáforo', distractors: null, explanation: 'Also called "sinal" in casual speech. "O sinal tá vermelho" = the light is red.', mineiro_note: null, tags: '["travel"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'bridge', answer: 'ponte', distractors: null, explanation: 'Feminine noun: "a ponte".', mineiro_note: null, tags: '["travel"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'travel', prompt: 'highway / road', answer: 'estrada', distractors: null, explanation: '"Estrada" = road/highway (general). "Rodovia" = numbered highway.', mineiro_note: 'Minas has beautiful estradas through the Serra da Mantiqueira.', tags: '["travel"]', difficulty: 2 }),

  // === VOCAB: Family (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'mother', answer: 'mãe', distractors: null, explanation: 'Informal: "mamãe". The ã nasal sound is key in Portuguese.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'father', answer: 'pai', distractors: null, explanation: 'Informal: "papai". Plural "pais" = parents.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'brother', answer: 'irmão', distractors: null, explanation: 'Feminine: "irmã". Plural: "irmãos" (siblings).', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'sister', answer: 'irmã', distractors: null, explanation: 'Note the nasal ã. Mineiros sometimes say "minha irmã" very quickly: "minhirmã".', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'grandfather', answer: 'avô', distractors: null, explanation: 'Closed ô sound. "Avó" (grandmother) has open ó sound. The accent matters!', mineiro_note: null, tags: '["family"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'grandmother', answer: 'avó', distractors: null, explanation: 'Open ó sound. Informal: "vovó". Mineiro grandmothers are legendary cooks.', mineiro_note: 'Comida de vó mineira é o melhor trem do mundo!', tags: '["family"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'cousin (male)', answer: 'primo', distractors: null, explanation: 'Female cousin: "prima". Same as Spanish.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'uncle', answer: 'tio', distractors: null, explanation: '"Tio" is also used informally to address older men you respect.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'aunt', answer: 'tia', distractors: null, explanation: '"Tia" is also used for female teachers by young children.', mineiro_note: null, tags: '["family"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'family', prompt: 'mother-in-law', answer: 'sogra', distractors: null, explanation: '"Sogro" = father-in-law. Brazilian culture has lots of sogra jokes!', mineiro_note: null, tags: '["family"]', difficulty: 2 }),

  // === VOCAB: Daily Routine (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to wake up', answer: 'acordar', distractors: null, explanation: 'False cognate alert! Spanish "acordar" = to agree/remember. PT "acordar" = to wake up.', mineiro_note: null, tags: '["daily_routine","false_cognate"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to brush teeth', answer: 'escovar os dentes', distractors: null, explanation: '"Escovar" = to brush. "Escova de dentes" = toothbrush.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to take a shower', answer: 'tomar banho', distractors: null, explanation: '"Tomar" here means "to take". Brazilians shower 2-3 times daily in hot weather.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'breakfast', answer: 'café da manhã', distractors: null, explanation: 'Literally "morning coffee". In Minas, breakfast is a lavish spread with cheese bread, cakes, and fruit.', mineiro_note: 'Café da manhã mineiro é famoso — queijo, pão de queijo, bolo, biscoito...', tags: '["daily_routine","food"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'lunch', answer: 'almoço', distractors: null, explanation: 'The main meal in Brazil, usually around noon-1pm. "Almoçar" = to have lunch.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'dinner', answer: 'jantar', distractors: null, explanation: 'Also the verb: "jantar" = to have dinner. Usually lighter than lunch.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to sleep', answer: 'dormir', distractors: null, explanation: 'Same as Spanish. "Estou com sono" = I\'m sleepy.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to work', answer: 'trabalhar', distractors: null, explanation: '"Trabalho" = work (noun). Similar to Spanish "trabajar".', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to rest', answer: 'descansar', distractors: null, explanation: 'Same as Spanish "descansar". "Preciso descansar" = I need to rest.', mineiro_note: null, tags: '["daily_routine"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'daily_routine', prompt: 'to cook', answer: 'cozinhar', distractors: null, explanation: '"Cozinha" = kitchen. Mineiros are proud of their cooking traditions.', mineiro_note: 'Cozinha mineira é patrimônio cultural!', tags: '["daily_routine"]', difficulty: 1 }),

  // === VOCAB: Body & Health (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'head', answer: 'cabeça', distractors: null, explanation: '"Dor de cabeça" = headache. Note the ç (cedilla).', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'arm', answer: 'braço', distractors: null, explanation: 'Note the ç. Plural: "braços".', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'leg', answer: 'perna', distractors: null, explanation: '"Perna" in Portuguese. Similar to Spanish "pierna".', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'stomachache', answer: 'dor de barriga', distractors: null, explanation: '"Barriga" = belly/stomach. "Dor" = pain.', mineiro_note: null, tags: '["body_health"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'fever', answer: 'febre', distractors: null, explanation: '"Estar com febre" = to have a fever. Uses ESTAR (temporary state).', mineiro_note: null, tags: '["body_health","ser_estar"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'medicine / remedy', answer: 'remédio', distractors: null, explanation: '"Tomar remédio" = to take medicine. "Remédio" is more common than "medicamento" in casual speech.', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'doctor\'s appointment', answer: 'consulta', distractors: null, explanation: '"Marcar uma consulta" = to schedule an appointment. Not to be confused with Spanish "consulta" (question).', mineiro_note: null, tags: '["body_health"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'hospital', answer: 'hospital', distractors: null, explanation: 'Same word, different pronunciation: stress on last syllable (hos-pi-TAL).', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'pharmacy', answer: 'farmácia', distractors: null, explanation: 'Also called "drogaria" for larger chain pharmacies in Brazil.', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'body_health', prompt: 'flu / cold', answer: 'gripe', distractors: null, explanation: '"Estar gripado" = to have the flu. Very common expression.', mineiro_note: null, tags: '["body_health"]', difficulty: 1 }),

  // === VOCAB: Emotions (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'happy', answer: 'feliz', distractors: null, explanation: 'Same for masculine and feminine. "Estou feliz" (uses ESTAR — current feeling).', mineiro_note: null, tags: '["emotions","ser_estar"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'sad', answer: 'triste', distractors: null, explanation: 'Same for both genders. "Estou triste" = I am sad (right now).', mineiro_note: null, tags: '["emotions"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'worried', answer: 'preocupado', distractors: null, explanation: 'Feminine: "preocupada". "Estou preocupado com..." = I\'m worried about...', mineiro_note: null, tags: '["emotions"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'excited / lively', answer: 'animado', distractors: null, explanation: '"Animado" in PT = excited/enthusiastic. NOT "animated" like in English.', mineiro_note: null, tags: '["emotions"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'missing someone / nostalgia (untranslatable)', answer: 'saudade', distractors: null, explanation: 'One of the most famous Portuguese words — a deep longing for something or someone absent. No direct English equivalent.', mineiro_note: 'Saudade is the soul of Portuguese music and poetry.', tags: '["emotions"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'nervous', answer: 'nervoso', distractors: null, explanation: 'Feminine: "nervosa". Can also mean angry in casual usage.', mineiro_note: null, tags: '["emotions"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'calm / chill', answer: 'tranquilo', distractors: null, explanation: '"Tranquilo" is used constantly in Brazil — as a response ("tá tranquilo" = it\'s all good), as reassurance.', mineiro_note: '"Fica tranquilo, sô!" = "Relax, dude!"', tags: '["emotions"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'proud', answer: 'orgulhoso', distractors: null, explanation: 'Feminine: "orgulhosa". "Tenho orgulho de..." = I\'m proud of...', mineiro_note: null, tags: '["emotions"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'embarrassed / ashamed', answer: 'envergonhado', distractors: null, explanation: 'This is the real "embarrassed" in PT — NOT "embaraçada" (which means pregnant).', mineiro_note: null, tags: '["emotions","false_cognate"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'emotions', prompt: 'tired', answer: 'cansado', distractors: null, explanation: 'Uses ESTAR: "Estou cansado" (temporary state, not identity).', mineiro_note: null, tags: '["emotions","ser_estar"]', difficulty: 1 }),

  // === VOCAB: Shopping (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'price', answer: 'preço', distractors: null, explanation: '"Qual é o preço?" = What\'s the price? Note the ç.', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'discount', answer: 'desconto', distractors: null, explanation: '"Tem desconto?" = Is there a discount? A must-know phrase for Brazilian markets.', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'expensive', answer: 'caro', distractors: null, explanation: 'Feminine: "cara". "Tá caro demais!" = It\'s too expensive!', mineiro_note: 'Mineiro: "Nó, que trem caro!"', tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'cheap / inexpensive', answer: 'barato', distractors: null, explanation: 'Feminine: "barata". But "barata" also means cockroach — context matters!', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'change (money returned)', answer: 'troco', distractors: null, explanation: '"Tem troco?" = Do you have change? Very common in small shops.', mineiro_note: null, tags: '["shopping"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'card (credit/debit)', answer: 'cartão', distractors: null, explanation: '"Aceita cartão?" = Do you accept card? Essential phrase.', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'cash / money', answer: 'dinheiro', distractors: null, explanation: '"Pagar em dinheiro" = to pay in cash. Pix is now more common than cash in Brazil.', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'bag (shopping bag)', answer: 'sacola', distractors: null, explanation: '"Sacola" = shopping/plastic bag. "Bolsa" = purse/handbag.', mineiro_note: null, tags: '["shopping"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'to try on (clothing)', answer: 'provar', distractors: null, explanation: '"Posso provar?" = Can I try it on? "Provador" = fitting room.', mineiro_note: null, tags: '["shopping"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'shopping', prompt: 'size (clothing)', answer: 'tamanho', distractors: null, explanation: '"Que tamanho você usa?" = What size do you wear?', mineiro_note: null, tags: '["shopping"]', difficulty: 1 }),

  // === VOCAB: Work (A2) ===
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'office', answer: 'escritório', distractors: null, explanation: 'Note the accent. "Trabalho no escritório" = I work in the office.', mineiro_note: null, tags: '["work"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'meeting', answer: 'reunião', distractors: null, explanation: '"Ter uma reunião" = to have a meeting. The ã nasal is important.', mineiro_note: null, tags: '["work"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'boss', answer: 'chefe', distractors: null, explanation: 'Same for male and female. Can also mean "chef" in a kitchen context.', mineiro_note: null, tags: '["work"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'colleague / coworker', answer: 'colega', distractors: null, explanation: '"Colega de trabalho" = work colleague. Gender-neutral noun.', mineiro_note: null, tags: '["work"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'work', prompt: 'salary', answer: 'salário', distractors: null, explanation: 'Similar to Spanish "salario". "Salário mínimo" = minimum wage.', mineiro_note: null, tags: '["work"]', difficulty: 1 }),

  // === CLOZE: More Ser vs Estar (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Eu ___ de Minas Gerais. (I am from MG — origin)', answer: 'sou', distractors: null, explanation: 'Use SER for origin/nationality. "Sou mineiro" = I am from Minas.', mineiro_note: '"Sou mineiro, uai!" — with pride!', tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'O tempo ___ frio hoje. (The weather is cold today — current)', answer: 'está', distractors: null, explanation: 'Use ESTAR for weather (temporary condition). "Está chovendo" = It is raining.', mineiro_note: null, tags: '["ser_estar"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'A festa ___ amanhã. (The party is tomorrow — scheduled event)', answer: 'é', distractors: null, explanation: 'Use SER for scheduled events, dates, and times. "A reunião é às 3" = The meeting is at 3.', mineiro_note: null, tags: '["ser_estar"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Ela ___ muito bonita hoje. (She looks very pretty today — temporary)', answer: 'está', distractors: null, explanation: 'ESTAR + bonita = looks pretty today (implies she doesn\'t always). SER + bonita = IS pretty (inherently).', mineiro_note: 'Subtle difference! "Ela é bonita" vs "Ela está bonita" changes meaning.', tags: '["ser_estar"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'ser_estar', prompt: 'Nós ___ amigos. (We are friends — relationship)', answer: 'somos', distractors: null, explanation: 'Use SER for relationships. "Somos amigos" = We are friends (ongoing relationship).', mineiro_note: null, tags: '["ser_estar"]', difficulty: 2 }),

  // === CLOZE: Present Tense Verbs (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ português todos os dias. (I study Portuguese every day — estudar)', answer: 'estudo', distractors: null, explanation: 'Regular -ar verb. Eu estudo, você estuda, nós estudamos.', mineiro_note: null, tags: '["verbs"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Ela ___ água. (She drinks water — beber)', answer: 'bebe', distractors: null, explanation: 'Regular -er verb. Eu bebo, você bebe, nós bebemos.', mineiro_note: null, tags: '["verbs"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Nós ___ no centro. (We live downtown — morar)', answer: 'moramos', distractors: null, explanation: 'Regular -ar verb. "Morar" = to live (reside). "Nós moramos" = we live.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ pão de queijo. (I want cheese bread — querer)', answer: 'quero', distractors: null, explanation: 'Irregular verb. Eu quero, você quer, nós queremos. Very common in daily speech.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eles ___ inglês e português. (They speak English and Portuguese — falar)', answer: 'falam', distractors: null, explanation: 'Regular -ar verb. "Eles falam" = they speak. In Mineiro casual speech: "falano" (dropping the d from gerund).', mineiro_note: 'Mineiro gerund: "tô falano" instead of "tô falando"', tags: '["verbs","mineiro"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ ao mercado. (I go to the market — ir)', answer: 'vou', distractors: null, explanation: 'Irregular verb "ir". Eu vou, você vai, nós vamos. "Vamos!" = Let\'s go!', mineiro_note: null, tags: '["verbs"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Você ___ onde fica o mercado? (Do you know where the market is? — saber)', answer: 'sabe', distractors: null, explanation: 'Irregular verb "saber" (to know facts). "Conhecer" = to know (be familiar with). Important distinction!', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ que a comida mineira é boa. (I think/find that Mineiro food is good — achar)', answer: 'acho', distractors: null, explanation: '"Achar" = to think/find (opinion) or to find (physically). "Eu acho que sim" = I think so.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Nós ___ café toda manhã. (We have/drink coffee every morning — tomar)', answer: 'tomamos', distractors: null, explanation: '"Tomar" = to take/have (drinks/meals). "Tomar café" = to drink coffee or to have breakfast.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_present', prompt: 'Eu ___ que você é mineiro. (I know/can tell you are Mineiro — perceber)', answer: 'percebo', distractors: null, explanation: '"Perceber" = to perceive/notice. NOT "to perceive" as suspect — that\'s more neutral in PT.', mineiro_note: null, tags: '["verbs"]', difficulty: 3 }),

  // === CLOZE: Past Tense Verbs (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Ontem eu ___ pão de queijo. (Yesterday I ate cheese bread — comer)', answer: 'comi', distractors: null, explanation: 'Preterite of "comer". Eu comi, você comeu, nós comemos.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Ela ___ com a mãe dela. (She spoke with her mother — falar)', answer: 'falou', distractors: null, explanation: 'Preterite of "falar". Eu falei, você falou, nós falamos.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Nós ___ para Ouro Preto. (We went to Ouro Preto — ir)', answer: 'fomos', distractors: null, explanation: 'Irregular preterite of "ir". Eu fui, você foi, nós fomos. Same forms as "ser" in preterite!', mineiro_note: 'Ouro Preto is a UNESCO World Heritage colonial town in Minas.', tags: '["verbs"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eu ___ um café. (I had/drank a coffee — tomar)', answer: 'tomei', distractors: null, explanation: 'Preterite of "tomar". Eu tomei, você tomou, nós tomamos.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Ele ___ no hospital. (He was at the hospital — estar)', answer: 'esteve', distractors: null, explanation: 'Irregular preterite of "estar". Eu estive, você esteve, nós estivemos.', mineiro_note: null, tags: '["verbs","ser_estar"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eu ___ muito ontem. (I studied a lot yesterday — estudar)', answer: 'estudei', distractors: null, explanation: 'Regular -ar preterite. Eu estudei, você estudou, nós estudamos.', mineiro_note: null, tags: '["verbs"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Você ___ o filme? (Did you watch the movie? — assistir)', answer: 'assistiu', distractors: null, explanation: 'Regular -ir preterite. "Assistir" in PT requires "a": "Assistir ao filme". But colloquially the "a" is often dropped.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eu ___ um presente para ela. (I bought a gift for her — comprar)', answer: 'comprei', distractors: null, explanation: 'Regular -ar preterite. Eu comprei, você comprou, nós compramos.', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eles ___ muito cedo. (They arrived very early — chegar)', answer: 'chegaram', distractors: null, explanation: 'Regular -ar preterite (3rd plural). Note: "chegar" uses "em" not "a" for arrival: "Chegaram em casa".', mineiro_note: null, tags: '["verbs"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'verbs_past', prompt: 'Eu não ___ nada. (I didn\'t do anything — fazer)', answer: 'fiz', distractors: null, explanation: 'Irregular preterite of "fazer". Eu fiz, você fez, nós fizemos. Very common verb!', mineiro_note: null, tags: '["verbs"]', difficulty: 3 }),

  // === CLOZE: More Prepositions (A2) ===
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'O café ___ Maria é bom. (Maria\'s coffee — possession)', answer: 'da', distractors: null, explanation: '"Da" = de + a (of the, feminine). "Do" = de + o (masculine).', mineiro_note: null, tags: '["preposition"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Isso é ___ você. (This is for you)', answer: 'para', distractors: null, explanation: '"Para" = for/to. Often shortened to "pra" in casual speech.', mineiro_note: 'Mineiro: "Isso é pra cê"', tags: '["preposition"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Ele passou ___ a porta. (He passed through the door)', answer: 'pela', distractors: null, explanation: '"Pela" = por + a. "Pelo" = por + o. Contractions with "por" (by/through).', mineiro_note: null, tags: '["preposition"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Vou ___ você. (I\'m going with you)', answer: 'com', distractors: null, explanation: '"Com" = with. "Comigo" = with me, "contigo" = with you (formal).', mineiro_note: null, tags: '["preposition"]', difficulty: 1 }),
  ex({ type: 'cloze', cefr_level: 'A2', topic: 'prepositions', prompt: 'Saí ___ dinheiro. (I left without money)', answer: 'sem', distractors: null, explanation: '"Sem" = without. Opposite of "com". "Sem problema" = no problem.', mineiro_note: null, tags: '["preposition"]', difficulty: 1 }),

  // === MULTIPLE CHOICE: More False Cognates (A2) ===
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "acordar" mean in Portuguese?', answer: 'to wake up', distractors: '["to agree","to record","to remember"]', explanation: 'False cognate! Spanish "acordar" = to agree/remember. PT "acordar" = to wake up. PT "agree" = "concordar".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "borracha" mean in Portuguese?', answer: 'eraser / rubber', distractors: '["drunk woman","bottle","rubber band"]', explanation: 'False cognate! Spanish "borracha" = drunk woman. PT "borracha" = eraser/rubber. PT "drunk" = "bêbada".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "pasta" mean in Portuguese?', answer: 'folder / briefcase', distractors: '["pasta (food)","paste","dough"]', explanation: 'False cognate! PT "pasta" = folder/briefcase. PT pasta (food) = "massa" or "macarrão".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "puxar" mean in Portuguese?', answer: 'to pull', distractors: '["to push","to punch","to rush"]', explanation: '"Puxar" = to pull. Looks like "push" but means the opposite! PT "push" = "empurrar".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'false_cognates', prompt: 'What does "largo" mean in Portuguese?', answer: 'wide / public square', distractors: '["long","large","far"]', explanation: 'PT "largo" = wide or a public square. PT "long" = "longo". PT "large" = "grande".', mineiro_note: null, tags: '["false_cognate"]', difficulty: 3 }),

  // === MULTIPLE CHOICE: Mineiro vs Standard BP (A2) ===
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'What is the standard BP equivalent of "Cê tá bão?"', answer: 'Você está bom?', distractors: '["Você é bom?","Você tem bom?","Você fica bom?"]', explanation: '"Cê" = você, "tá" = está, "bão" = bom. Classic Mineiro contraction.', mineiro_note: 'This is THE Mineiro greeting. You\'ll hear it dozens of times a day.', tags: '["mineiro"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'What does "Ô sô, cê viu aquele trem?" mean?', answer: 'Hey dude, did you see that thing?', distractors: '["Oh sir, you saw that train?","Hey you, did you watch that show?","Oh dear, you lost your thing?"]', explanation: '"Sô" = dude (vocative), "cê" = you, "viu" = saw, "trem" = thing (not train!).', mineiro_note: null, tags: '["mineiro"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'In Mineiro speech, how would you say "falando" (speaking)?', answer: 'falano', distractors: '["falando","falanho","falão"]', explanation: 'Mineiros drop the "d" from gerunds: falando→falano, comendo→comeno, fazendo→fazeno.', mineiro_note: 'This is one of the most distinctive Mineiro speech patterns.', tags: '["mineiro"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'What does "Nó!" express in Mineiro?', answer: 'Surprise or amazement (like "wow!")', distractors: '["A knot","No / denial","A problem"]', explanation: '"Nó" is short for "Nossa Senhora!" (Our Lady!). Used to express surprise, amazement, or shock.', mineiro_note: '"Nó, que trem bão!" = "Wow, what a great thing!"', tags: '["mineiro"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'mineiro_vs_standard', prompt: 'What does "uai" typically express?', answer: 'Surprise, agreement, or used as a filler word', distractors: '["Sadness","Anger","A question"]', explanation: '"Uai" is the most versatile Mineiro word — surprise, emphasis, agreement, or just filler. Like "like" in California English.', mineiro_note: null, tags: '["mineiro"]', difficulty: 1 }),

  // === MULTIPLE CHOICE: Cultural Knowledge (A2) ===
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What is the capital of Minas Gerais?', answer: 'Belo Horizonte', distractors: '["São Paulo","Ouro Preto","Tiradentes"]', explanation: 'Belo Horizonte (BH) became the capital in 1897, replacing Ouro Preto. It\'s Brazil\'s 3rd largest metro area.', mineiro_note: null, tags: '["cultural"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What does "Minas Gerais" literally mean?', answer: 'General Mines', distractors: '["My Generals","Mining Town","Beautiful Mountains"]', explanation: 'Named for the abundant gold and gemstone mines discovered in the 18th century. "Minas" = mines, "Gerais" = general.', mineiro_note: null, tags: '["cultural"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What is "pão de queijo" made from?', answer: 'Tapioca starch (polvilho) and cheese', distractors: '["Wheat flour and cheese","Cornmeal and milk","Rice flour and butter"]', explanation: 'Polvilho (tapioca/cassava starch) gives pão de queijo its unique chewy texture. Wheat flour is never used.', mineiro_note: null, tags: '["cultural","food"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What is Ouro Preto famous for?', answer: 'Colonial baroque architecture and gold mining history', distractors: '["Beaches and surfing","Modern skyscrapers","Coffee plantations"]', explanation: 'Ouro Preto is a UNESCO World Heritage Site, the heart of Brazil\'s 18th-century gold rush. "Ouro" = gold, "Preto" = black.', mineiro_note: null, tags: '["cultural"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'cultural', prompt: 'What is a "boteco" in Minas?', answer: 'A casual bar / neighborhood pub', distractors: '["A type of cheese","A dance style","A traditional hat"]', explanation: '"Boteco" (or "buteco") is a casual neighborhood bar serving beer, cachaça, and petiscos (snacks). Central to Mineiro social life.', mineiro_note: 'BH has an annual "Comida di Buteco" festival — a boteco food competition!', tags: '["cultural"]', difficulty: 2 }),

  // === ERROR CORRECTION (A2) ===
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu sou cansado.', answer: 'Eu estou cansado.', distractors: null, explanation: '"Tired" is a temporary state → use ESTAR, not SER. "Sou cansado" would mean you ARE a tired person by nature.', mineiro_note: null, tags: '["ser_estar","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Ela é em Belo Horizonte.', answer: 'Ela está em Belo Horizonte.', distractors: null, explanation: 'Location uses ESTAR, not SER. "Ela é de BH" (origin) vs "Ela está em BH" (current location).', mineiro_note: null, tags: '["ser_estar","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu moro a Belo Horizonte.', answer: 'Eu moro em Belo Horizonte.', distractors: null, explanation: '"Morar" takes the preposition "em" (in), not "a". Spanish uses "en" similarly.', mineiro_note: null, tags: '["preposition","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'O polvo é muito bom para limpar.', answer: 'A poeira é muito boa para limpar.', distractors: null, explanation: '"Polvo" = octopus, not dust! Dust = "poeira". And "poeira" is feminine → "boa", not "bom".', mineiro_note: null, tags: '["false_cognate","error_correction"]', difficulty: 3 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu estou embaraçado.', answer: 'Eu estou envergonhado.', distractors: null, explanation: '"Embaraçado" means pregnant (for women) or tangled, NOT embarrassed. Use "envergonhado" for embarrassed.', mineiro_note: null, tags: '["false_cognate","error_correction"]', difficulty: 3 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'A menina bonito chegou.', answer: 'A menina bonita chegou.', distractors: null, explanation: 'Gender agreement: "menina" (girl) is feminine → "bonita" (not "bonito"). Adjectives must match the noun\'s gender.', mineiro_note: null, tags: '["grammar","error_correction"]', difficulty: 1 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu vou ao mercado para comprar leites.', answer: 'Eu vou ao mercado para comprar leite.', distractors: null, explanation: '"Leite" (milk) is uncountable — no plural. "Comprar leite" not "leites". For bottles: "garrafas de leite".', mineiro_note: null, tags: '["grammar","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu gosto de ela.', answer: 'Eu gosto dela.', distractors: null, explanation: '"De" + "ela" contracts to "dela". Portuguese prepositions always contract with pronouns: dele, dela, deles, delas.', mineiro_note: null, tags: '["grammar","error_correction"]', difficulty: 2 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu tenho vinte e um anos.', answer: 'Eu tenho vinte e um anos.', distractors: null, explanation: 'Trick question! This sentence is correct. Portuguese uses "ter" (to have) for age, just like Spanish. NOT "ser" like in English.', mineiro_note: null, tags: '["grammar","error_correction"]', difficulty: 1 }),
  ex({ type: 'error_correction', cefr_level: 'A2', topic: 'error_correction', prompt: 'Eu puxei a porta para abrir.', answer: 'Eu empurrei a porta para abrir.', distractors: null, explanation: '"Puxar" = to PULL, not push! If you\'re opening a door by pushing, use "empurrar". Classic false friend with English "push".', mineiro_note: null, tags: '["false_cognate","error_correction"]', difficulty: 2 }),

  // === B1 CONTENT ===
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'emotions', prompt: 'to miss (feel saudade for someone)', answer: 'sentir falta', distractors: null, explanation: '"Sinto falta de você" = I miss you. More specific than "saudade" — focuses on the absence.', mineiro_note: null, tags: '["emotions","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'work', prompt: 'to resign / quit a job', answer: 'pedir demissão', distractors: null, explanation: '"Pedir" = to ask for, "demissão" = dismissal. You ASK FOR your own dismissal. "Ser demitido" = to be fired.', mineiro_note: null, tags: '["work","B1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'daily_routine', prompt: 'to be running late', answer: 'estar atrasado', distractors: null, explanation: '"Atrasado" = late/delayed. Uses ESTAR (temporary state). "Desculpa, estou atrasado" = Sorry, I\'m running late.', mineiro_note: null, tags: '["daily_routine","ser_estar","B1"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'verbs_present', prompt: 'Se eu ___ dinheiro, eu viajava. (If I had money, I would travel — ter, imperfect subjunctive)', answer: 'tivesse', distractors: null, explanation: 'Imperfect subjunctive of "ter". Used in hypothetical/conditional sentences: "Se eu tivesse..."', mineiro_note: null, tags: '["verbs","subjunctive","B1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'verbs_present', prompt: 'Espero que você ___ bem. (I hope you are well — estar, present subjunctive)', answer: 'esteja', distractors: null, explanation: 'Present subjunctive of "estar". After "espero que" (I hope that), use subjunctive.', mineiro_note: null, tags: '["verbs","subjunctive","B1"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'cultural', prompt: 'What is "Inconfidência Mineira"?', answer: 'An 18th-century independence movement in Minas Gerais', distractors: '["A type of Mineiro music","A colonial church in Ouro Preto","A traditional festival"]', explanation: 'The 1789 conspiracy against Portuguese colonial rule, led by Tiradentes (Joaquim José da Silva Xavier). He was executed and became a national hero.', mineiro_note: 'Tiradentes is a national holiday (April 21) and a beautiful colonial town in Minas.', tags: '["cultural","B1"]', difficulty: 3 }),

  // === MORE B1 CONTENT ===

  // B1 Vocab: Abstract concepts & daily life
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'emotions', prompt: 'to get along with someone', answer: 'se dar bem com', distractors: null, explanation: '"Dar-se bem" = to get along. "Eu me dou bem com ele" = I get along with him. Reflexive verb.', mineiro_note: null, tags: '["emotions","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'emotions', prompt: 'to be fed up / sick of something', answer: 'estar de saco cheio', distractors: null, explanation: 'Colloquial expression. "Tô de saco cheio desse trânsito" = I\'m sick of this traffic. Informal but very common.', mineiro_note: '"Tô de saco cheio desse trem" — Mineiro version', tags: '["emotions","B1"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'daily_routine', prompt: 'to get stuck in traffic', answer: 'ficar preso no trânsito', distractors: null, explanation: '"Trânsito" = traffic. "Ficar preso" = to get stuck. A daily reality in Brazilian cities.', mineiro_note: null, tags: '["daily_routine","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'daily_routine', prompt: 'to oversleep', answer: 'dormir demais', distractors: null, explanation: '"Dormir demais" = to sleep too much / oversleep. "Perder a hora" = to lose track of time (also used for oversleeping).', mineiro_note: null, tags: '["daily_routine","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'work', prompt: 'deadline', answer: 'prazo', distractors: null, explanation: '"Prazo" = deadline/term. "O prazo é amanhã" = The deadline is tomorrow. "Prazo de validade" = expiration date.', mineiro_note: null, tags: '["work","B1"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'work', prompt: 'to be promoted', answer: 'ser promovido', distractors: null, explanation: '"Promoção" = promotion. "Ele foi promovido" = He was promoted. Uses passive voice with SER.', mineiro_note: null, tags: '["work","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'travel', prompt: 'to miss a flight/bus', answer: 'perder o voo/ônibus', distractors: null, explanation: '"Perder" = to lose OR to miss (transport). "Perdi o ônibus" = I missed the bus. Context determines meaning.', mineiro_note: null, tags: '["travel","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'travel', prompt: 'to check in (hotel/airport)', answer: 'fazer o check-in', distractors: null, explanation: 'English loanword used in Brazilian Portuguese. "Fazer o check-in" or just "checar" in some contexts.', mineiro_note: null, tags: '["travel","B1"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'body_health', prompt: 'to schedule an appointment', answer: 'marcar uma consulta', distractors: null, explanation: '"Marcar" = to schedule/book. "Consulta" = appointment (medical). "Marcar hora" = general appointment.', mineiro_note: null, tags: '["body_health","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'body_health', prompt: 'prescription', answer: 'receita', distractors: null, explanation: '"Receita" = prescription OR recipe! Context matters. "Receita médica" = medical prescription. "Receita de bolo" = cake recipe.', mineiro_note: null, tags: '["body_health","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'shopping', prompt: 'to exchange/return (a product)', answer: 'trocar/devolver', distractors: null, explanation: '"Trocar" = to exchange (for another). "Devolver" = to return (for refund). "Posso trocar?" = Can I exchange this?', mineiro_note: null, tags: '["shopping","B1"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B1', topic: 'shopping', prompt: 'installment payments', answer: 'parcelas', distractors: null, explanation: '"Pagar em parcelas" = to pay in installments. Very common in Brazil. "Em quantas vezes?" = In how many installments?', mineiro_note: null, tags: '["shopping","B1"]', difficulty: 3 }),

  // B1 Cloze: Subjunctive & Imperfect
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'verbs_present', prompt: 'É importante que você ___ português. (It\'s important that you study Portuguese — estudar, present subjunctive)', answer: 'estude', distractors: null, explanation: 'Present subjunctive of "estudar". After "é importante que" use subjunctive. Regular -ar → -e ending.', mineiro_note: null, tags: '["verbs","subjunctive","B1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'verbs_present', prompt: 'Duvido que ele ___ a verdade. (I doubt he knows the truth — saber, present subjunctive)', answer: 'saiba', distractors: null, explanation: 'Irregular present subjunctive of "saber". After "duvido que" (I doubt that), always use subjunctive.', mineiro_note: null, tags: '["verbs","subjunctive","B1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'verbs_past', prompt: 'Quando eu era criança, eu ___ muito. (When I was a child, I played a lot — brincar, imperfect)', answer: 'brincava', distractors: null, explanation: 'Imperfect tense of "brincar". Used for habitual past actions. "Eu brincava" = I used to play.', mineiro_note: null, tags: '["verbs","imperfect","B1"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'verbs_past', prompt: 'Ele ___ quando eu cheguei. (He was sleeping when I arrived — dormir, imperfect)', answer: 'dormia', distractors: null, explanation: 'Imperfect of "dormir". Imperfect = ongoing action in the past, interrupted by a preterite action.', mineiro_note: null, tags: '["verbs","imperfect","B1"]', difficulty: 2 }),
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'verbs_past', prompt: 'Nós ___ todos os dias na fazenda. (We used to walk every day on the farm — andar, imperfect)', answer: 'andávamos', distractors: null, explanation: 'Imperfect of "andar" (1st person plural). Regular -ar imperfect: -ava, -avas, -ava, -ávamos, -avam.', mineiro_note: 'Fazenda in Minas can mean farm or ranch — many families have one in the interior.', tags: '["verbs","imperfect","B1"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B1', topic: 'ser_estar', prompt: 'Quando eu era jovem, eu ___ muito magro. (When I was young, I was very thin — ser, imperfect)', answer: 'era', distractors: null, explanation: 'Imperfect of "ser". "Era" for ongoing past characteristics. "Fui" (preterite) for completed events.', mineiro_note: null, tags: '["ser_estar","imperfect","B1"]', difficulty: 2 }),

  // B1 Multiple Choice
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'false_cognates', prompt: 'What does "pretender" mean in Portuguese?', answer: 'to intend / to plan', distractors: '["to pretend","to prevent","to predict"]', explanation: 'False cognate! PT "pretender" = to intend/plan. PT "pretend" = "fingir". "Pretendo viajar" = I intend to travel.', mineiro_note: null, tags: '["false_cognate","B1"]', difficulty: 3 }),
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'false_cognates', prompt: 'What does "assistir" mean in Portuguese?', answer: 'to watch / to attend', distractors: '["to assist","to help","to support"]', explanation: 'False cognate! PT "assistir" = to watch/attend. PT "assist/help" = "ajudar". "Assistir ao jogo" = to watch the game.', mineiro_note: null, tags: '["false_cognate","B1"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'cultural', prompt: 'What is "cachaça"?', answer: 'A sugarcane spirit, the base of caipirinha', distractors: '["A type of cheese","A Mineiro dance","A traditional dessert"]', explanation: 'Cachaça is Brazil\'s national spirit, distilled from sugarcane. Minas Gerais produces some of the finest artisanal cachaças.', mineiro_note: 'Minas has the "Rota da Cachaça" — a tourist trail of artisanal distilleries in Salinas.', tags: '["cultural","B1"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'mineiro_vs_standard', prompt: 'What does "trem bão demais da conta" mean?', answer: 'Something really, really great', distractors: '["A very expensive train","Too much food","An old vehicle"]', explanation: '"Trem" = thing, "bão" = good, "demais da conta" = way too much. Classic Mineiro superlative expression.', mineiro_note: 'This is peak Mineiro enthusiasm. Used for food, people, places — anything amazing.', tags: '["mineiro","B1"]', difficulty: 2 }),

  // B1 Error Correction
  ex({ type: 'error_correction', cefr_level: 'B1', topic: 'error_correction', prompt: 'Eu pretendo fingir que estou doente.', answer: 'Eu pretendo fingir que estou doente.', distractors: null, explanation: 'Trick! This sentence is actually correct. "Pretendo" = I intend, "fingir" = to pretend. The trap is thinking "pretendo" means "pretend".', mineiro_note: null, tags: '["false_cognate","error_correction","B1"]', difficulty: 3 }),
  ex({ type: 'error_correction', cefr_level: 'B1', topic: 'error_correction', prompt: 'Se eu tinha dinheiro, eu comprava uma casa.', answer: 'Se eu tivesse dinheiro, eu compraria uma casa.', distractors: null, explanation: 'Hypothetical conditional requires imperfect subjunctive (tivesse) + conditional (compraria). "Se eu tinha" is colloquially accepted but grammatically incorrect.', mineiro_note: 'In casual Mineiro speech, "Se eu tinha" IS used — but the formal form is tivesse/compraria.', tags: '["grammar","subjunctive","error_correction","B1"]', difficulty: 3 }),
  ex({ type: 'error_correction', cefr_level: 'B1', topic: 'error_correction', prompt: 'Eu assisti o filme ontem.', answer: 'Eu assisti ao filme ontem.', distractors: null, explanation: '"Assistir" requires the preposition "a" — "assistir ao filme", not "assistir o filme". This is a common mistake even native speakers make.', mineiro_note: null, tags: '["grammar","error_correction","B1"]', difficulty: 2 }),

  // === B2 CONTENT ===

  // B2 Vocab: Nuanced expressions
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to be at a loss for words / speechless', answer: 'ficar sem palavras', distractors: null, explanation: '"Ficar sem palavras" = to be left without words. More formal: "ficar estupefato" (stunned).', mineiro_note: '"Nó, fiquei sem palavras!" — classic Mineiro reaction', tags: '["emotions","B2"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'emotions', prompt: 'to hold a grudge', answer: 'guardar rancor', distractors: null, explanation: '"Guardar" = to keep/hold, "rancor" = grudge/resentment. "Não guardo rancor" = I don\'t hold grudges.', mineiro_note: null, tags: '["emotions","B2"]', difficulty: 3 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'work', prompt: 'to be overloaded with work', answer: 'estar sobrecarregado', distractors: null, explanation: '"Sobrecarregado" = overloaded. "Estou sobrecarregado de trabalho" = I\'m overloaded with work.', mineiro_note: null, tags: '["work","B2"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'work', prompt: 'to network (professionally)', answer: 'fazer networking', distractors: null, explanation: 'English loanword commonly used in Brazilian Portuguese. Also: "fazer contatos profissionais".', mineiro_note: null, tags: '["work","B2"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'daily_routine', prompt: 'to procrastinate', answer: 'procrastinar', distractors: null, explanation: 'Same root as English. Very commonly used in Brazilian Portuguese. "Parei de procrastinar" = I stopped procrastinating.', mineiro_note: null, tags: '["daily_routine","B2"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'B2', topic: 'mineiro', prompt: '"old man" / "buddy" (affectionate Mineiro slang)', answer: 'véio', distractors: null, explanation: 'Contracted from "velho" (old). Used affectionately between friends regardless of age. "E aí, véio!" = Hey buddy!', mineiro_note: '"Ô véio, cê tá sumido!" = "Hey buddy, you disappeared!"', tags: '["mineiro","B2"]', difficulty: 2 }),

  // B2 Cloze: Advanced grammar
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'verbs_present', prompt: 'Embora ele ___ inteligente, não passou no exame. (Although he is intelligent, he didn\'t pass — ser, present subjunctive)', answer: 'seja', distractors: null, explanation: '"Embora" (although) always triggers subjunctive. "Seja" = present subjunctive of "ser".', mineiro_note: null, tags: '["verbs","subjunctive","B2"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'verbs_past', prompt: 'Depois que eles ___, nós fomos embora. (After they left, we left — sair, past subjunctive/pluperfect)', answer: 'saíram', distractors: null, explanation: 'Preterite of "sair" (3rd plural). "Depois que" + indicative describes a completed sequence of events.', mineiro_note: null, tags: '["verbs","B2"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'verbs_present', prompt: 'Ela fala como se ___ brasileira. (She speaks as if she were Brazilian — ser, imperfect subjunctive)', answer: 'fosse', distractors: null, explanation: '"Como se" (as if) always requires imperfect subjunctive. "Fosse" = imperfect subjunctive of "ser".', mineiro_note: null, tags: '["verbs","subjunctive","B2"]', difficulty: 3 }),
  ex({ type: 'cloze', cefr_level: 'B2', topic: 'prepositions', prompt: 'Apesar ___ chuva, fomos ao parque. (Despite the rain, we went to the park)', answer: 'da', distractors: null, explanation: '"Apesar de" = despite. "Da" = de + a (contraction with feminine "chuva"). Complex preposition usage.', mineiro_note: null, tags: '["preposition","B2"]', difficulty: 2 }),

  // B2 Multiple Choice
  ex({ type: 'multiple_choice', cefr_level: 'B2', topic: 'cultural', prompt: 'What is "Clube da Esquina"?', answer: 'A legendary music movement from Minas Gerais (Milton Nascimento)', distractors: '["A soccer club from BH","A Mineiro cooking school","A political party"]', explanation: 'Clube da Esquina is one of the most influential music movements in Brazilian history, centered in BH. Led by Milton Nascimento, Lô Borges, and others in the 1970s.', mineiro_note: 'Milton Nascimento is Minas\'s greatest musician — his voice is iconic worldwide.', tags: '["cultural","B2"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'B2', topic: 'cultural', prompt: 'What does "mineiridade" refer to?', answer: 'The cultural identity and character traits of people from Minas Gerais', distractors: '["A type of mineral","The mining industry","A political movement"]', explanation: '"Mineiridade" encompasses discretion, hospitality, love of food, religious tradition, and a reserved but warm personality. Mineiros are known for being reserved but deeply loyal.', mineiro_note: '"Mineiro não fala o que pensa, mas pensa muito no que fala" — a famous saying about Mineiro discretion.', tags: '["cultural","B2"]', difficulty: 3 }),

  // ============================================================
  // TRUE/FALSE EXERCISES
  // ============================================================

  ex({ type: 'true_false', cefr_level: 'A2', topic: 'true_false', prompt: '"Trem" in Mineiro Portuguese means "train".', answer: 'false', distractors: null, explanation: 'False! In standard BP, "trem" means train. But in Mineiro, "trem" means "thing" — anything at all. "Esse trem" = "that thing".', mineiro_note: null, tags: '["mineiro","true_false"]', difficulty: 1 }),
  ex({ type: 'true_false', cefr_level: 'A2', topic: 'true_false', prompt: '"Bom dia" is used as a greeting in the morning.', answer: 'true', distractors: null, explanation: 'True! "Bom dia" (good day/morning) is used until around noon.', mineiro_note: null, tags: '["greetings","true_false"]', difficulty: 1 }),
  ex({ type: 'true_false', cefr_level: 'A2', topic: 'true_false', prompt: '"Estou cansado" uses SER because tiredness is a permanent trait.', answer: 'false', distractors: null, explanation: 'False! Tiredness is a temporary state → use ESTAR. "Sou cansado" would mean "I am a tired person by nature".', mineiro_note: null, tags: '["ser_estar","true_false"]', difficulty: 2 }),
  ex({ type: 'true_false', cefr_level: 'A2', topic: 'true_false', prompt: 'In Portuguese, "embaraçada" means "embarrassed".', answer: 'false', distractors: null, explanation: 'False! "Embaraçada" means pregnant (or tangled). "Embarrassed" = "envergonhada". Classic false cognate!', mineiro_note: null, tags: '["false_cognate","true_false"]', difficulty: 2 }),
  ex({ type: 'true_false', cefr_level: 'A2', topic: 'true_false', prompt: '"Puxar" means "to pull" in Portuguese.', answer: 'true', distractors: null, explanation: 'True! "Puxar" = to pull. It looks like "push" but means the opposite! "Empurrar" = to push.', mineiro_note: null, tags: '["false_cognate","true_false"]', difficulty: 2 }),
  ex({ type: 'true_false', cefr_level: 'A2', topic: 'true_false', prompt: 'Mineiros typically drop the "d" in gerunds: "falando" becomes "falano".', answer: 'true', distractors: null, explanation: 'True! This is one of the most distinctive Mineiro speech features. Comendo→comeno, fazendo→fazeno.', mineiro_note: null, tags: '["mineiro","true_false"]', difficulty: 1 }),
  ex({ type: 'true_false', cefr_level: 'A2', topic: 'true_false', prompt: '"Obrigado" and "obrigada" mean the same thing.', answer: 'true', distractors: null, explanation: 'True! Both mean "thank you" — "obrigado" is used by male speakers, "obrigada" by female speakers. The meaning is identical.', mineiro_note: null, tags: '["greetings","true_false"]', difficulty: 1 }),
  ex({ type: 'true_false', cefr_level: 'B1', topic: 'true_false', prompt: '"Assistir" in Portuguese means "to assist someone".', answer: 'false', distractors: null, explanation: 'False! "Assistir" = to watch/attend. "Assistir ao jogo" = to watch the game. "To assist" = "ajudar".', mineiro_note: null, tags: '["false_cognate","true_false","B1"]', difficulty: 2 }),
  ex({ type: 'true_false', cefr_level: 'B1', topic: 'true_false', prompt: 'The imperfect tense is used for habitual past actions in Portuguese.', answer: 'true', distractors: null, explanation: 'True! "Eu brincava" = I used to play. The imperfect describes ongoing, habitual, or repeated past actions.', mineiro_note: null, tags: '["verbs","true_false","B1"]', difficulty: 2 }),
  ex({ type: 'true_false', cefr_level: 'B1', topic: 'true_false', prompt: '"Pretender" in Portuguese means "to pretend".', answer: 'false', distractors: null, explanation: 'False! "Pretender" = to intend/plan. "Pretendo viajar" = I intend to travel. "To pretend" = "fingir".', mineiro_note: null, tags: '["false_cognate","true_false","B1"]', difficulty: 3 }),

  // ============================================================
  // SENTENCE REORDERING EXERCISES
  // ============================================================

  ex({ type: 'reorder', cefr_level: 'A2', topic: 'reorder', prompt: 'queijo / de / pão / quero / eu', answer: 'eu quero pão de queijo', distractors: null, explanation: 'Subject (eu) + verb (quero) + object (pão de queijo). Standard Portuguese word order.', mineiro_note: null, tags: '["food","reorder"]', difficulty: 1 }),
  ex({ type: 'reorder', cefr_level: 'A2', topic: 'reorder', prompt: 'em / moro / Horizonte / Belo / eu', answer: 'eu moro em belo horizonte', distractors: null, explanation: '"Morar em" = to live in. Subject + verb + preposition + place.', mineiro_note: null, tags: '["travel","reorder"]', difficulty: 1 }),
  ex({ type: 'reorder', cefr_level: 'A2', topic: 'reorder', prompt: 'consulta / uma / marcar / preciso / eu', answer: 'eu preciso marcar uma consulta', distractors: null, explanation: 'Subject + "precisar" + infinitive + object. "Preciso marcar" = I need to schedule.', mineiro_note: null, tags: '["body_health","reorder"]', difficulty: 2 }),
  ex({ type: 'reorder', cefr_level: 'A2', topic: 'reorder', prompt: 'muito / café / o / está / quente', answer: 'o café está muito quente', distractors: null, explanation: 'Article + noun + ESTAR + adverb + adjective. "Está" because hot is a temporary state.', mineiro_note: null, tags: '["ser_estar","reorder"]', difficulty: 2 }),
  ex({ type: 'reorder', cefr_level: 'A2', topic: 'reorder', prompt: 'feira / vou / ao / mercado / da', answer: 'vou ao mercado da feira', distractors: null, explanation: '"Ir ao" = to go to the. "Da feira" = of the market/fair. Contractions: ao = a+o, da = de+a.', mineiro_note: null, tags: '["shopping","reorder"]', difficulty: 2 }),
  ex({ type: 'reorder', cefr_level: 'A2', topic: 'reorder', prompt: 'irmã / minha / professora / é', answer: 'minha irmã é professora', distractors: null, explanation: 'Possessive + noun + SER + profession. "É" because profession is a permanent characteristic.', mineiro_note: null, tags: '["family","reorder"]', difficulty: 1 }),
  ex({ type: 'reorder', cefr_level: 'B1', topic: 'reorder', prompt: 'tivesse / dinheiro / se / eu / viajaria / eu', answer: 'se eu tivesse dinheiro eu viajaria', distractors: null, explanation: 'Conditional structure: Se + imperfect subjunctive + conditional. "Se eu tivesse... eu viajaria."', mineiro_note: null, tags: '["verbs","reorder","B1"]', difficulty: 3 }),
  ex({ type: 'reorder', cefr_level: 'B1', topic: 'reorder', prompt: 'que / espero / bem / esteja / você', answer: 'espero que você esteja bem', distractors: null, explanation: '"Espero que" triggers subjunctive. "Esteja" = present subjunctive of "estar".', mineiro_note: null, tags: '["verbs","reorder","B1"]', difficulty: 3 }),

  // ============================================================
  // DIALOGUE EXERCISES (read and answer about conversations)
  // ============================================================

  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'dialogue', prompt: 'At a boteco:\nGarçom: "Boa noite! O que vai ser?"\nCliente: "Me vê uma cerveja bem gelada e um tira-gosto."\n\nWhat did the customer order?', answer: 'A cold beer and a snack', distractors: '["Hot coffee and cake","Water and bread","Juice and sandwich"]', explanation: '"Cerveja bem gelada" = very cold beer. "Tira-gosto" = appetizer/snack (literally "taste-remover"). Classic boteco order!', mineiro_note: '"Me vê" is casual Mineiro for "give me" — very common in bars.', tags: '["dialogue","food"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'dialogue', prompt: 'Giving directions:\nTurista: "Com licença, onde fica o Mercado Central?"\nMineiro: "Cê segue reto aqui, vira na segunda esquina à direita. Tá pertinho, uai!"\n\nWhat should the tourist do?', answer: 'Go straight and turn right at the second corner', distractors: '["Turn left at the first corner","Go back two blocks","Take the bus"]', explanation: '"Segue reto" = go straight. "Vira na segunda esquina à direita" = turn at the second corner to the right. "Pertinho" = very close (diminutive).', mineiro_note: '"Tá pertinho, uai!" — typical Mineiro reassurance. Everything is "pertinho" in Minas.', tags: '["dialogue","travel"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'dialogue', prompt: 'At a shop:\nCliente: "Quanto custa essa camisa?"\nVendedor: "Essa tá R$89,90. Mas se levar duas, faço R$150."\nCliente: "Aceita cartão?"\nVendedor: "Aceito sim, débito e crédito."\n\nHow much for two shirts?', answer: 'R$150', distractors: '["R$89,90","R$179,80","R$200"]', explanation: 'The vendor offers a discount: "Se levar duas, faço R$150" = If you take two, I\'ll do R$150. Haggling is common!', mineiro_note: null, tags: '["dialogue","shopping"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'dialogue', prompt: 'At the doctor:\nPaciente: "Doutor, tô com uma dor de cabeça forte há três dias."\nMédico: "Cê tá tomando algum remédio?"\nPaciente: "Só dipirona, mas não tá resolvendo."\nMédico: "Vou passar um exame de sangue pra gente investigar."\n\nWhat does the doctor decide?', answer: 'Order a blood test to investigate', distractors: '["Prescribe stronger pain medicine","Send the patient home","Recommend surgery"]', explanation: '"Passar um exame" = to order a test. "Exame de sangue" = blood test. "Pra gente investigar" = for us to investigate.', mineiro_note: 'Notice the doctor uses "cê" (Mineiro informal) — common even in professional settings in Minas.', tags: '["dialogue","body_health","B1"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'dialogue', prompt: 'Catching up with a friend:\nAna: "Ô sô, quanto tempo! Cê sumiu!"\nCarlos: "Pois é, tava viajando. Fui pra Ouro Preto."\nAna: "Nó! E como foi?"\nCarlos: "Trem bão demais da conta! A comida então, nem te conto."\n\nHow does Carlos describe his trip?', answer: 'Really great, especially the food', distractors: '["Boring and expensive","Too short","The weather was bad"]', explanation: '"Trem bão demais da conta" = really, really great (peak Mineiro enthusiasm). "Nem te conto" = don\'t even get me started (it was amazing).', mineiro_note: 'This dialogue is 100% Mineiro: sô, cê, nó, trem bão, demais da conta.', tags: '["dialogue","mineiro","B1"]', difficulty: 2 }),

  // ============================================================
  // MORE DIALOGUES
  // ============================================================

  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'dialogue', prompt: 'At a restaurant:\nGarçom: "Boa tarde! Mesa pra quantos?"\nCliente: "Pra dois, por favor. Tem mesa na varanda?"\nGarçom: "Tem sim! Me acompanhe."\n\nWhat does the customer want?', answer: 'A table for two on the terrace', distractors: '["A table for four inside","A takeaway order","A reservation for tomorrow"]', explanation: '"Mesa pra dois" = table for two. "Varanda" = terrace/patio. "Me acompanhe" = follow me.', mineiro_note: null, tags: '["dialogue","food"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'A2', topic: 'dialogue', prompt: 'On the phone:\nAna: "Alô?"\nCarlos: "Oi Ana, é o Carlos. Cê tá ocupada?"\nAna: "Agora tô um pouco. Posso te ligar daqui a pouco?"\nCarlos: "Claro, sem problema!"\n\nWhat does Ana say?', answer: 'She is busy now but will call back later', distractors: '["She wants to meet right away","She is free to talk","She does not want to talk"]', explanation: '"Tô um pouco" (ocupada implied) = I\'m a bit (busy). "Daqui a pouco" = in a little while. "Te ligar" = call you.', mineiro_note: null, tags: '["dialogue","daily_routine"]', difficulty: 1 }),
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'dialogue', prompt: 'Job interview:\nEntrevistador: "Me fale sobre sua experiência."\nCandidato: "Trabalhei cinco anos como analista. Tenho experiência com gestão de projetos e atendimento ao cliente."\nEntrevistador: "E por que quer mudar de emprego?"\nCandidato: "Busco novos desafios e oportunidades de crescimento."\n\nWhy does the candidate want to change jobs?', answer: 'Looking for new challenges and growth opportunities', distractors: '["Unhappy with salary","Problems with boss","Company is closing"]', explanation: '"Busco novos desafios" = I seek new challenges. "Crescimento" = growth. This is a polished, professional answer.', mineiro_note: null, tags: '["dialogue","work","B1"]', difficulty: 2 }),
  ex({ type: 'multiple_choice', cefr_level: 'B1', topic: 'dialogue', prompt: 'Complaining at a hotel:\nHóspede: "Com licença, tem um problema com meu quarto."\nRecepcionista: "O que aconteceu?"\nHóspede: "O ar condicionado não está funcionando e o chuveiro tá pingando."\nRecepcionista: "Peço desculpas! Vou trocar o senhor de quarto imediatamente."\n\nWhat solution does the receptionist offer?', answer: 'Change the guest to a different room', distractors: '["Send a technician tomorrow","Offer a discount","Apologize but do nothing"]', explanation: '"Trocar de quarto" = change rooms. "Imediatamente" = immediately. Professional service response.', mineiro_note: null, tags: '["dialogue","travel","B1"]', difficulty: 2 }),

  // ============================================================
  // MORE VOCAB: Numbers, Time, Weather, Colors
  // ============================================================

  ex({ type: 'vocab', cefr_level: 'A2', topic: 'time_numbers', prompt: 'What time is it? (asking)', answer: 'que horas são?', distractors: null, explanation: '"Que horas são?" = What time is it? Always plural in Portuguese (são), even for 1:00 ("é uma hora").', mineiro_note: null, tags: '["time"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'time_numbers', prompt: 'yesterday', answer: 'ontem', distractors: null, explanation: '"Ontem" = yesterday. "Anteontem" = day before yesterday.', mineiro_note: null, tags: '["time"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'time_numbers', prompt: 'tomorrow', answer: 'amanhã', distractors: null, explanation: '"Amanhã" = tomorrow. "Depois de amanhã" = day after tomorrow.', mineiro_note: null, tags: '["time"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'time_numbers', prompt: 'next week', answer: 'semana que vem', distractors: null, explanation: '"Semana que vem" = next week. "Semana passada" = last week.', mineiro_note: null, tags: '["time"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'time_numbers', prompt: 'early / on time / late', answer: 'cedo / na hora / atrasado', distractors: null, explanation: '"Chegar cedo" = arrive early. "Na hora" = on time. "Atrasado" = late.', mineiro_note: null, tags: '["time"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'weather', prompt: 'it\'s raining', answer: 'está chovendo', distractors: null, explanation: '"Chover" = to rain. Uses ESTAR (current state). "Tá chovendo" in casual speech.', mineiro_note: 'Mineiro: "Tá choveno" (dropping the d from gerund)', tags: '["weather","ser_estar"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'weather', prompt: 'it\'s hot / it\'s cold', answer: 'está quente / está frio', distractors: null, explanation: 'Weather uses ESTAR. "Tá quente demais!" = It\'s too hot!', mineiro_note: null, tags: '["weather","ser_estar"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'weather', prompt: 'sunny', answer: 'ensolarado', distractors: null, explanation: '"Sol" = sun. "Ensolarado" = sunny. "Dia ensolarado" = sunny day.', mineiro_note: null, tags: '["weather"]', difficulty: 2 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'colors', prompt: 'red / blue / green', answer: 'vermelho / azul / verde', distractors: null, explanation: 'Colors agree with gender: "camisa vermelha" (f) but "carro vermelho" (m). Azul/verde don\'t change.', mineiro_note: null, tags: '["colors"]', difficulty: 1 }),
  ex({ type: 'vocab', cefr_level: 'A2', topic: 'colors', prompt: 'white / black / yellow', answer: 'branco / preto / amarelo', distractors: null, explanation: 'All agree with gender: branca/preta/amarela (feminine). "Ouro Preto" = Black Gold (the city name).', mineiro_note: null, tags: '["colors"]', difficulty: 1 }),

  // ============================================================
  // MORE TRUE/FALSE
  // ============================================================

  ex({ type: 'true_false', cefr_level: 'A2', topic: 'true_false', prompt: '"Que horas são?" is the correct way to ask the time in Portuguese.', answer: 'true', distractors: null, explanation: 'True! "Que horas são?" uses the plural because it refers to multiple hours. Even at 1:00 you say "É uma hora" (singular).', mineiro_note: null, tags: '["time","true_false"]', difficulty: 1 }),
  ex({ type: 'true_false', cefr_level: 'A2', topic: 'true_false', prompt: 'In Portuguese, colors always stay the same regardless of the noun\'s gender.', answer: 'false', distractors: null, explanation: 'False! Most colors change with gender: vermelho/vermelha, branco/branca, preto/preta. But "azul" and "verde" stay the same.', mineiro_note: null, tags: '["colors","true_false"]', difficulty: 2 }),
  ex({ type: 'true_false', cefr_level: 'B1', topic: 'true_false', prompt: 'After "embora" (although), you must use the subjunctive mood.', answer: 'true', distractors: null, explanation: 'True! "Embora" always triggers subjunctive: "Embora ele seja inteligente..." (not "é").', mineiro_note: null, tags: '["verbs","subjunctive","true_false","B1"]', difficulty: 3 }),
  ex({ type: 'true_false', cefr_level: 'B1', topic: 'true_false', prompt: '"Receita" in Portuguese only means "recipe".', answer: 'false', distractors: null, explanation: 'False! "Receita" means BOTH recipe AND prescription. "Receita médica" = medical prescription. "Receita de bolo" = cake recipe.', mineiro_note: null, tags: '["body_health","true_false","B1"]', difficulty: 2 }),

  // ============================================================
  // MORE REORDER
  // ============================================================

  ex({ type: 'reorder', cefr_level: 'A2', topic: 'reorder', prompt: 'chovendo / está / muito / hoje', answer: 'está chovendo muito hoje', distractors: null, explanation: 'ESTAR + gerund for ongoing action. "Está chovendo muito" = It\'s raining a lot.', mineiro_note: null, tags: '["weather","reorder"]', difficulty: 1 }),
  ex({ type: 'reorder', cefr_level: 'A2', topic: 'reorder', prompt: 'horas / que / são / ?', answer: 'que horas são?', distractors: null, explanation: 'Question word "que" + "horas" + verb "são". Standard question structure.', mineiro_note: null, tags: '["time","reorder"]', difficulty: 1 }),
  ex({ type: 'reorder', cefr_level: 'B1', topic: 'reorder', prompt: 'que / importante / é / estude / você', answer: 'é importante que você estude', distractors: null, explanation: '"É importante que" + subjunctive. "Estude" = present subjunctive of "estudar".', mineiro_note: null, tags: '["verbs","subjunctive","reorder","B1"]', difficulty: 3 }),
  ex({ type: 'reorder', cefr_level: 'B1', topic: 'reorder', prompt: 'embora / chova / vou / sair / eu', answer: 'embora chova eu vou sair', distractors: null, explanation: '"Embora" (although) + subjunctive "chova" + main clause. Complex B1 structure.', mineiro_note: null, tags: '["verbs","subjunctive","reorder","B1"]', difficulty: 3 }),
];
